### ISSUE TITLE
Pertea Protocol

### ISSUE THREAD

**Issue by notadeny** [gpertea/stringtie#101]
Hello,

I hope this is something easy to fix, but I cannot find a solution. I'm following the practice protocol found in Pertea 2016, and encountered a problem with the label placement in the stringtie section. I've tried searching and switching the flags around, moving my working directory, searching on the web (can't find solution). I don't understand why it needs a file for index placement.

Here is what I am encountering:

$ stringtie ../bamfiles/ERR188104_chrX.bam -G ~/data/trial/chrX_data/genes/chrX.gtf –l ERR188104 -o ERR188104_chrX.gtf -p 8
Error: input file –l cannot be found!
Aborted (core dumped)

Thanks in advance!

**Comment by gpertea** [comment]
This sounds similar to the problem raised in https://github.com/gpertea/gffcompare/issues/3 - unfortunately during the preparation of the document for publication, some characters (like the simple '-' (minus, dash) character) have been converted into their typographical/UTF8 equivalents, which are non-functional. 

In effect people trying to simply copy&paste the commands from the paper to a terminal might not realize that instead of using normal '-' character (for the `-l` option in your example above), they're using a non-ASCII 'dash' character (`–l` , notice the longer line) which is **not** recognized by any program as an option marker. 

So if you modify the command and actually type all those dash characters directly with your keyboard (by using the *minus* symbol on the keyboard), instead of copying&pasting it from the protocol, it should work. We apologize for the confusion, we haven't noticed that this transformation happened during the final editing of the protocol for publication.

**Comment by notadeny** [comment]
Oh, I see. My apologies for my naivete, that was indeed the problem.

Thank you so much for your response!
