### ISSUE TITLE
Questions about `prepDE.py`

### ISSUE THREAD

**Issue by dennisroberts71** [gpertea/stringtie#104]
Some of our users are running into a case where an exception is randomly being thrown because a regular expression isn't matching a line in one of the files matched by the glob expression. The exception is random because the glob expression searches for files with a `.gtf` extension, which matches two different files in each sample directory. The first file is `<sample-name>.gtf` and the second file is `<sample-name>.refs.gtf`. The exception is random because the files aren't always returned in the same order. If the `<sample-name>.gtf` file is matched by the glob pattern first, then the script works correctly. If the `<sample-name>.refs.gtf` file is matched by the glob pattern first then the exception occurs.

Digging into the files themselves reveals the cause of the error. The `<sample-name>.gtf` file contains lines that will match the regular expressions used to extract the transcript ID and the gene ID whereas `<sample-name>.refs.gtf` does not. What I'd like to know is whether the data set is incorrect or if the script should not match the `<sample-name>.refs.gtf` files. My assumption is that the program should not match these files, but I have no way of knowing that just from looking at the code; I only know that the script seems to work correctly when it does not match these files. If the script is not supposed to match these files then I should be able to fix it easily enough and submit a pull request, but I wanted to make sure that this was the right thing to do first.

I had one other question only because I'm not a bioinformatician and I don't know exactly what this script is supposed to do. The loop that sets up `badGenes` only scans the first GTF file in the first sample that it finds, but I was unable to figure out why it only scans this one file. Is there only supposed to be one GTF file if the `--cluster` option is selected? Is there something special abut the data set that indicates that only the first GTF file will ever contain bad genes? Is the set of genes (and thus the set of bad genes) supposed to be the same in each of the GTF files in the sample?

Finally, do you have some sets of test data that I can run this script against to verify that it's working correctly? If I'm going to submit a pull request then I'd like to have some confidence that my changes haven't broken anything.

**Comment by gpertea** [comment]
Thank you for the detailed description of the issue. The cause of the problems you experienced there seems to be the fact that prepDE expects to find *only one* `*.gtf` file in each sample directory (the only output of StringTie that prepDE needs). So you are right in assuming that it shouldn't have matched the `.refs.gtf` file at all -- because no other `*.gtf` file was supposed to be there! Not sure how that additional `*.refs.gtf` file ends up within each sample directory, I would guess that could be a common resource for all those StringTie runs (a reference set of transcripts?) but in that case it should have been placed in a common directory somewhere else (instead of being replicated in each sample directory) which would've prevented this failure. Sure the python code can be patched specifically for this situation as to skip/ignore the `*.refs.gtf` file if it's the first match, as you correctly suggested -- and this seems like a local modification of the script for your particular situation there, as whoever designed the pipeline there somehow decided to place those additional `*.refs.gtf` file in there for each sample, which is not how the original protocol was designed. 

About your second question: all GTF files processed by prepDE (i.e. the `<sample-name>.gtf`) should have the same set of genes (i.e.  same set of values for the "gene_id" attribute). This is why prepDE can get the list of genes from any of the input files -- so we decided to simply pick the first file for this, it is as simple as that -- but the `--cluster` option still expects multiple samples, because that's how prepDE works anyway (on multiple samples, with a `.gtf` file for each sample). Of course this assumption breaks if the pipeline there wasn't designed properly, i.e. if the StringTie runs which generated the `<sample-name>.gtf` files did not use the exact same reference transcript file as input (so I'm actually hoping that the `<sample-name>.refs.gtf` file, which confused prepDE as I explained above, was *not* that reference input file, or if it was, that all these files are identical across all samples..). You should be able to see the command line that was used to generate the `<sample-name>.gtf` file in the "header" line at the beginning of this file (I hope it doesn't use `-G <sample-name>.refs.gtf` there, because that would break the pipeline unless all those `<sample-name>.refs.gtf` are identical.. in which case it would be a waste to place a copy of it in each sample directory)

**Comment by gpertea** [comment]
To address your very last question: I don't have a test data set for you to test at the moment though I guess you could use/generate the example data set which came with the protocol paper, you can look into `ftp://ftp.ccb.jhu.edu/pub/RNAseq_protocol/` for that. The `chrX_data.tar.gz` file there can be used to generate a small test data set for prepDE.py .. but the protocol described there must be followed in order to get those final .gtf files for each sample (the shell and R scripts found in that ftp directory should help with that). 

However I don't think you need to prepare a pull request, as I suggested earlier I think it's better just to fix prepDE there on your end in order to ignore those extraneous `*.refs.gtf` files. We currently have a student revising prepDE a bit as to provide an alternate, more targeted way to specifiy the input GTF file for each sample so problems like these should be easily avoided by using that alternate input specification.

**Comment by dennisroberts71** [comment]
Thanks for your responses. I think this gives me enough information to correct the problem on our end.
