### ISSUE TITLE
StringTie with gencode gtf

### ISSUE THREAD

**Issue by zoewardnz** [gpertea/stringtie#108]
Hi,
I am using StringTie v1.3.3 and gencodev25.
When I run stringtie with my gencode.gtf it is not producing any reads in the output sample gtf for reads covering the gencode.gtf. E.g. I know I have many reads for the gene NPPA:
 
![image](https://cloud.githubusercontent.com/assets/26702571/24341081/a93aabde-1313-11e7-96fc-8d292354be08.png)

But when I look at the **output sample gtf** all of the ENSEMBL transcripts are "FPKM=0", "COV=0" but there _is_ coverage for the Stringtie assembled transcripts. e.g.
1       **ENSEMBL** transcript      11845712        11847783        .       -       .       gene_id "ENSG00000175206.10"; transcript_id "ENST00000610706.1"; ref_gene_name "NPPA"; cov "0.0"; FPKM "0.000000"; TPM "0.000000";
1       **ENSEMBL** exon    11845712        11846014        .       -       .       gene_id "ENSG00000175206.10"; transcript_id "ENST00000610706.1"; exon_number "1"; ref_gene_name "NPPA"; cov "0.0";
1       **ENSEMBL** exon    11847113        11847439        .       -       .       gene_id "ENSG00000175206.10"; transcript_id "ENST00000610706.1"; exon_number "2"; ref_gene_name "NPPA"; cov "0.0";
1       **ENSEMBL** exon    11847562        11847783        .       -       .       gene_id "ENSG00000175206.10"; transcript_id "ENST00000610706.1"; exon_number "3"; ref_gene_name "NPPA"; cov "0.0";
1       **StringTie**       transcript      11845709        11847783        1000    -       .       gene_id "ENSG00000175206.10"; transcript_id "ENST00000376480.7"; ref_gene_name "NPPA"; cov "1509.049805"; FPKM "825.903259"; TPM "3305.021729";
1       **StringTie**       exon    11845709        11846014        1000    -       .       gene_id "ENSG00000175206.10"; transcript_id "ENST00000376480.7"; exon_number "1"; ref_gene_name "NPPA"; cov "9.476404";
1       **StringTie**       exon    11847113        11847439        1000    -       .       gene_id "ENSG00000175206.10"; transcript_id "ENST00000376480.7"; exon_number "2"; ref_gene_name "NPPA"; cov "12.135779";
1       **StringTie**       exon    11847562        11847783        1000    -       .       gene_id "ENSG00000175206.10"; transcript_id "ENST00000376480.7"; exon_number "3"; ref_gene_name "NPPA"; cov "5780.943359";

Surely Stringtie should recognise these reads from genes present in the annotation file?? I find it hard to believe that _all_ of my reads are novel transcripts for this gene (and all of the others from gencode.gtf)

Thanks.

**Comment by gpertea** [comment]
Not sure I understand the problem here (and the picture is not clear enough to figure out what's what), but from the two transcripts you showed above it looks like StringTie actually assembled a *known* isoform (ENST00000376480.7) and assigned all the reads to it (hence the other known isoforms for the same gene got 0 coverage). I am not sure why you think that would be a **novel** transcript -- the 2nd column that you highlighted there simply indicates that StringTie worked on assembling that isoform (which happens to match perfectly a known isoform). Novel transcripts have a different naming convention for transcript_id in StringTie's output,  so the fact that here you see a *known* Ensembl transcript_id for those lines means that it is not a *novel* transcript.

**Comment by zoewardnz** [comment]
Hi Mihaela,  Thanks for you reply, that has helped to explain things to me. I do have a further question (and perhaps this should have been the one I asked first). The screen shot below shows the reads for one sample for one of the genes that we are highly confident should be expressed in our sample:
![image](https://cloud.githubusercontent.com/assets/26702571/24387556/4db7dc9a-13d2-11e7-8ce8-a1ab2562be55.png)

If I look at the sample.gtf then I get the following:
1       StringTie       transcript      11857464        11858931        .       -       .       gene_id "MSTRG.348"; transcript_id "ENST00000376468.3"; ref_gene_name "NPPB"; cov "0.0"; FPKM "0.000000"; TPM "0.000000";
1       StringTie       exon    11857464        11857671        .       -       .       gene_id "MSTRG.348"; transcript_id "ENST00000376468.3"; exon_number "1"; ref_gene_name "NPPB"; cov "0.0";
1       StringTie       exon    11858214        11858469        .       -       .       gene_id "MSTRG.348"; transcript_id "ENST00000376468.3"; exon_number "2"; ref_gene_name "NPPB"; cov "0.0";
1       StringTie       exon    11858702        11858931        .       -       .       gene_id "MSTRG.348"; transcript_id "ENST00000376468.3"; exon_number "3"; ref_gene_name "NPPB"; cov "0.0";
1       StringTie       transcript      11857438        11859030        1000    -       .       gene_id "MSTRG.348"; transcript_id "MSTRG.348.1"; cov "120.390114"; FPKM "40.516884"; TPM "77.676590";
1       StringTie       exon    11857438        11859030        1000    -       .       gene_id "MSTRG.348"; transcript_id "MSTRG.348.1"; exon_number "1"; cov "120.390114";
My understanding is that stringtie is calling this transcript novel, am I correct? 
From the IGV screenshot it looks as though there are alot of reads (there are many more when you scroll down in IGV) aligning at each of the three exons that stringtie isn't calling??
Thanks, 
Zoe.

**Comment by gpertea** [comment]
Indeed, it looks like there are many *spliced* reads which seem to align to/span those 3 exons. Something seems fishy there if StringTie couldn't call a multi-exon transcript from those.. instead it called a big blob which covers the whole transcript region, including introns.

First I have to ask: how did you generate the read alignments? (what aligner, what options) Because one possible cause for missing these spliced alignments might be if the aligner was run with some default option which would not generate the XS tag for spliced alignments. StringTie discards any spliced alignments which lack the XS tag (unless specific library types are involved), and this might explain this situation.

Secondly, this also reminds me of the problem we had for older Gencode annotation files where a "gene" would be loaded as a single-exon transcript (and sometimes even a transcript could have been loaded as a separate entry, without exons/introns). Can you tell me precisely which Gencode annotation file you used for this run? (file name please, as you downloaded it from Gencode, it must end with either .gtf.gz or .gff3.gz). If you modified the Gencode file in any way (besides uncompressing), I would like to see how the reference Gencode transcripts look for that particular gene.

I see that the novel transcripts have the MSTRG prefix in their name, which seems to suggest they are the output of stringtie --merge, which complicates a bit the investigation here. Can you locate the StringTie's GTF output for that initial assembly of that particular sample that you loaded in IGV for the screenshot above? Was that output generated with an older version of StringTie ?

**Comment by zoewardnz** [comment]
HI,

Thanks for your email. I used the STAR aligner and went back to double check my commands. 
I entered the command to generate the XS tag for spliced reads but it looks as though there was a typo so it didn't actually  generate any SAM files with XS tags. So it looks like hopefully I have the answer thanks to your help. I will re-run everything and let you know the outcome.
Thanks again for your advice, Zoe.

**Comment by zoewardnz** [comment]
Hi Mihaela, Good news - I went back and did the alignment with the corrected command which generated the XS tags. My spliced reads are now being assembled and it's all looking good.
Thanks again for you help.

**Comment by zoewardnz** [comment]
Hi,
I think I still have the same issue as my previous correspondence.
After running prepDE.py most of my gene_count_matrix contains MSTRG ids (a minority will have the ENSG label but all of these have very low counts).

So if I pull out a gene ‘NPPB’ that I expect to be expressed from one of the sample gtf files I get:
1       StringTie       transcript      11857464        11858931        1000    -       .       gene_id "MSTRG.302"; transcript_id "ENST00000376468.3"; ref_gene_name "NPPB"; cov "2872.672607"; FPKM "706.683228"; TPM "1319.054688";
1       StringTie       exon    11857464        11857671        1000    -       .       gene_id "MSTRG.302"; transcript_id "ENST00000376468.3"; exon_number "1";                                 ref_gene_name "NPPB"; cov "1537.971313";
1       StringTie       exon    11858214        11858469        1000    -       .       gene_id "MSTRG.302"; transcript_id "ENST00000376468.3"; exon_number "2";                                 ref_gene_name "NPPB"; cov "3781.166992";
1       StringTie       exon    11858702        11858931        1000    -       .       gene_id "MSTRG.302"; transcript_id "ENST00000376468.3"; exon_number "3";                                 ref_gene_name "NPPB"; cov "3068.511963";

And so in the gene_count_matrix it is listed as MSTRG.302.


I think your second point (from the email below) may be relevant. I downloaded gencode from ftp://ftp.sanger.ac.uk/pub/gencode/Gencode_human/release_25/gencode.v25.primary_assembly.annotation.gtf.gz

I then modified the gtf file as the alignment didn’t seem to like that the chromosomes were labelled differently to the fasta file i.e. chr1 and not 1.
I therefore removed the ‘chr’ i.e. ‘chr1’ to ‘1’ and changed ‘Mt’ to ‘M’ for the mitochondria from the gencode.gtf ($ sed 's/chr//' gencode.gtf, $ sed ‘s/Mt/M/’gencode.gtf).

But I’m guessing if this is an issue then none of the genes in the gene_count_matrix would have a ENGS label??

Zoe.
