### ISSUE TITLE
LongReads.fq.gz

### ISSUE THREAD

**Issue by tiramisutes** [gpertea/stringtie#11]
![longreads](https://cloud.githubusercontent.com/assets/10768210/7024414/4e5de248-dd6f-11e4-8d02-faa71fadfa4e.png)

why i can't use gunzip to unzip the  <superreads.pl script> produced LongReads.fq.gz?

**Comment by gpertea** [comment]
Well, it might be a misleading (incorrectly assigned) file name, or the file might be zero-length due to some failure in the program ? You provided no other info about this silly error -- e.g. what was your *superreads.pl* command line? Is the file actually uncompressed? 

I would suggest that, before rushing to post a zero-info question about a simple error message like this, it might be more informative to actually take a closer look at the file yourself in order to at least partly alleviate this "big mystery" (is the file un/compressed ?). But do let us know if it seems that it was indeed our script mistakenly naming the file with a .gz extension in spite of being a regular, uncompressed file..
