### ISSUE TITLE
class code incorrect??

### ISSUE THREAD

**Issue by zoewardnz** [gpertea/stringtie#123]
Hi,

I have run gffcompare against my stringtie_merged.gtf to obtain the class codes.  
I am interested in one particular transcript that gives class code "o" (exon of predicted transcript overlaps a reference transcript) with the gene CTD-2201G16.1 but when I look at the co-ordinates they do not overlap.

```
14      StringTie       transcript      23388848        23418455        .       +       .       transcript_id "MSTRG.9386.1"; gene_id "MSTRG.9386"; gene_name "CTD-2201G16.1"; xloc "XLOC_015944"; cmp_ref "ENST00000557368.1"; class_code "o"; tss_id "TSS36161";
14      StringTie       exon    23388848        23389004        .       +       .       transcript_id "MSTRG.9386.1"; gene_id "MSTRG.9386"; exon_number "1";
14      StringTie       exon    23418356        23418455        .       +       .       transcript_id "MSTRG.9386.1"; gene_id "MSTRG.9386"; exon_number "2";
```

```
CTD-2201G16.1:
Exon 1:     23,415,339	23,415,464
Exon 2: 	23,415,606	23,415,686
```

Do you think gffcompare has assign class code "o" because the MSTRG transcript completely overlaps CTD-2201G16.1??? (even though the exons do not overlap)

**Comment by gpertea** [comment]
Interesting situation, it seems that the code *'o'* was simply assigned here because the other choices of overlap codes have been exhausted for this particular kind of "overlap". It looks like this is some sort of a reversal of the *'i'* code, because the reference transcript is fully contained within the intron of an assembled transcript (instead of the other way around), which is something that simply hasn't been considered before in gffcompare, it seems.

This is a gffcompare issue so I'll have to add a new overlap code for this situation (perhaps *'y'* ?) for this reverse intronic inclusion..

**Comment by zoewardnz** [comment]
Hi,

Just a quick question.

Should the GENE count matrix that is produced by the prep.DE.py script be the same if you do the  fast protocol compared to the longer (with stringtie merge) protocol??
Thanks,
Zoe.

**Comment by gpertea** [comment]
Not sure I understand your question, obviously the two pipelines are not estimating the same gene list.. The "fast" protocol only takes a set of known genes (transcript) while the complete protocol takes a combination of known and novel transcripts -- and potentially novel genes, possibly. There is also the possibility that the gene regions (boundaries) are different in the "complete" protocol, so very likely the coverage values won't look the same even if the same genes (same gene list) were being estimated in both cases..

Back to the topic, class code 'y' has been added to gffcompare for the situation described in this issue, the github master branch here already has it; I'm going to release a precompiled version soon on the CCB website, so I'm closing this.
