### ISSUE TITLE
Query on FPKM calculation

### ISSUE THREAD

**Issue by srithegreat** [gpertea/stringtie#15]
Hi Geo,

When I use the -e option in stringtie, are the FPKM calculations done based on reads mapped to the provided GTF or total mapped reads in the BAM file? 
I am trying to calculate the FPKM of only protein-coding genes (as a GTF), but I was wondering if the FPKM values also contain reads mapping to non-coding regions.

Srikanth

**Comment by gpertea** [comment]
(Sorry for the late reply) Looking at the code now, it seems that the FPKM calculation should not really change with the -e option, as currently that option is mostly an output filter - it limits the output to only show those assemblies which fully reconstructed any of the given reference transcripts.

Now I realize that the current description of this -e option in the manual may be misleading, suggesting that even the abundance estimation could be affected by considering only the alignments to the given transcripts (which might have been true at some point in an older version, I am not quite sure), but right now it only means that the estimation is only *shown* for those matching transcripts (simply because only those assemblies are going to be present in the output).

**Comment by mpertea** [comment]
The -e option now (version 1.1.0) only uses reads mapped to the annotated transcripts provided. So FPKMs values are computed only using these mappings.
