### ISSUE TITLE
Stringtie only processed chr1

### ISSUE THREAD

**Issue by tmelia** [gpertea/stringtie#16]
Hi, 

I ran stringtie v1.0.4 successfully on all of my samples except for one. For this sample, stringtie only processed chr1 and exited without any error. There's nothing particularly different with this sample. I am able to run cufflinks on all samples, i.e. including the sample that stringtie has a problem with. I'm wondering if you can help me to figure this out. I dont see any error message anywhere?

Here's how I ran stringtie:
stringtie mapped.bam -G genes.gtf -o output.gtf -p 4 -m 50 -C output.cov -B -c 0.001 -v

Here's the log for that particular run
[06/29 15:07:48] Loading reference annotation (guides)..
GFF warning: merging adjacent/overlapping segments of NM_001267620 on chr1 (75188734-75189163, 75189165-75189252)
GFF warning: merging adjacent/overlapping segments of NM_026187 on chr1 (75188734-75189163, 75189165-75189252)
....[truncated]
[06/29 15:07:58]>bundle chr1:16091376-16094514(21295) (3js, 1 guides) loaded, begins processing...
[06/29 15:07:58] 258732 aligned fragments found.
[06/29 15:07:59]^bundle chr1:16091376-16094514(21295) done (3 processed potential transcripts).
[06/29 15:07:59] All threads finished.
Total count of aligned fragments: 258732
Average fragment length:196.838

Thanks,
Tisha

**Comment by gpertea** [comment]
I suppose you tried this more than once on that .bam file and it was the same (in order to eliminate the possibility of an unlikely random I/O glitch which prematurely terminated the reading of the BAM file). Otherwise could it be that there are not enough alignments on the other chromosomes for Stringtie to build bundles..? (Unlikely for a normal sample, I agree).

It is very strange and it would be great if you can let us have a look at that BAM file.. Could you upload it using anonymous ftp to ftp.ccb.jhu.edu under /incoming/gpertea/ ?

**Comment by tmelia** [comment]
Hi Geo,

Thanks for the reply. I figured it out. It turned out that the bam file is corrupted. Sorry. I didnt look thoroughly at the bam file as cufflinks gave gene models in all of the chromosomes, which turned out to be mainly copied from the annotation file. Problem is fixed.

Thanks so much, 
Tisha
