### ISSUE TITLE
gene id incorrect?

### ISSUE THREAD

**Issue by zoewardnz** [gpertea/stringtie#161]
I have run stringtie merge and I then use stringtie_merged.gtf to compare to the gencode annotation with gffcompare. 
There are ~ 1000 transcripts that are not being given a class code. For example when I create a transcript count matrix (with prepDE.py) transcript ENST00000640668.1 has read counts for all samples in the transcript count matrix but has no class code. When I search for this transcript in stringtie merged.gtf  it appears as the gene id MSTRG.27131:
`chr22   StringTie       transcript      38485935        38506237        gene_id "MSTRG.27131"; transcript_id "ENST00000640668.1"; gene_name "DDX17"; ref_gene_id "ENSG00000100201.20";`
When I look at each exon of this transcript and compare it to the genocde.gtf all of the co-ordinates exactly match so should stingtie be giving it 'gene_id' DDX17 instead? Is this why gffcompare is not giving it an '=' class code???

**Comment by gpertea** [comment]
These are two unrelated issues.
1) gffcompare assigns class codes to *transcripts* based on their relationship with *reference transcripts*
Strangely enough, the one you mention, ENST00000640668.1 is a Gencode transcript so it should get the ```=``` code if you indeed used gffcompare with Gencode as the reference annotation.  How did you run gffcompare? Were the input files correctly formatted ? (including the reference annotation file, presumably the full Gencode annotation file). I would double check that because, I repeat, that IS a Gencode transcript and it should really get the ```=``` class code. If you are sure this is a bug in gffcompare please provide the example input data and the command line you used in a separate issue in https://github.com/gpertea/gffcompare/issues 
2) completely unrelated to the above, _gene_id_ and _gene_name_ have very different meanings in annotation - _gene_id_ is meant to be an unique identifier for a locus with overlapping transcripts, and because StringTie cannot assume (or spend time verifying) that the user has provided a reference annotation with consistent and unique gene_ids, StringTie assigns its own internally generated gene_ids which are thus guaranteed to be unique and functionally consistent. The users should use their own downstream post-processing in order to match these gene_ids with the desired gene_name, ref_gene_id or whatever they wish..
