### ISSUE TITLE
Calculation of coverage value

### ISSUE THREAD

**Issue by surajmetha55** [gpertea/stringtie#162]
How coverage is calculated by stringtie and what  range of coverage value (or acceptable value of coverage)

**Comment by gpertea** [comment]
Besides the vagueness of the question (and I'm not sure what you meant by "acceptable value of coverage", I don't think there is such a thing), some explanations should already be available in the related publications (and this "Issues" forum is not quite the place to ask for these rather basic notions). Have you read the paper describing how StringTie works ? (https://www.nature.com/articles/nbt.3122). 
For even more foundational details on the basics of RNA-Seq analysis I also recommend the original Cufflinks paper (from 2010), including its rich Supplemental Text and Figures.

**Comment by surajmetha55** [comment]
Had you have answered my question pointing towards the exact calculation, it would have helped me in the right way. What do you mean by "some explanations"? 

Have you read the paper describing how StringTie works ? (https://www.nature.com/articles/nbt.3122).
- Short answer, YES. Please point to the page number where I can find the same.

this "Issues" forum is not quite the place to ask for these rather basic notions
- Oh really? What's the best way then? For your information, people are asking similar questions on biostars.org; unfortunately no one has the answer. For e.g. see below posts:

https://www.biostars.org/p/292440/
https://www.biostars.org/p/263273/

Any help would be appreciated.

**Comment by lakhujanivijay** [comment]
I am surprised that the post was closed without answering the question. This is really sad!!

I am also waiting for the answer just as the thousands others working with StringTie. 

Hope to see some positive answer in the right attitude. 

Thanks!

**Comment by gpertea** [comment]
Vijay,
Please consider that there is nothing "sad" about the authors' decision to limit the use of this github board to bug reports, feature requests and other potential "issues" [sic] related to StringTie's code and functionality, instead of somehow being expected (_forced?_) to engage in answering [vague or seemingly basic] questions for which potentially complex answers are better provided by studying the related literature -- or indeed, by discussing them in wider public forums like Biostars. I thought some basic respect for authors' time and their free software support decisions would be implied in this public interaction on *their* github repository.

(Answering mostly to you here, as the other poster's answer suggested a sense of entitlement and a lack of respect which is not really worth further comments.)

The "coverage" notion here is "basic" in the sense that the formula is well known (it's just the average base coverage across an exon/transcript), but the original question does have a complex answer as to how the final coverage values are produced by StringTie, due to reasons such as:
- potential filtering of some of the read alignments 
- weighing down the per-base coverage contribution of multi-mapped reads
- most importantly for multi-transcript genes: distributing the reads among overlapping transcripts according to the maximum flow algorithm

The last point is the main reason I pointed to the paper (as I wasn't sure what to make of the original question here..). Most people who read the paper and understand the points above would not just ask the question like it was asked here.
However you or others are always welcome to come here and point out any specific problems ("issues") you may see with the calculation/estimation of the coverage values as produced by StringTie (after really considering the points above) and we'll be glad to take a look at the evidence, check for a potential "issues" with our code etc.

**Comment by lakhujanivijay** [comment]
First of all, we all highly appreciate the efforts to come up with tools like this. And thanks so much for taking time to respond. 

> 
Please consider that there is nothing "sad" about the authors' decision to limit the use of this github board to bug reports, feature requests and other potential "issues" [sic] related to StringTie's code and functionality, instead of somehow being expected (forced?) to engage in answering [vague or seemingly basic] questions for which potentially complex answers are better provided by studying the related literature -- or indeed, by discussing them in wider public forums like Biostars.

It is perfectly acceptable and understood that github is meant to be used for bugs and feature requests tracking. In fact, the first thing one would do for questions like this was to got to biostars.org and look there and which was actually done in this case. You can look for the posting dates. What may seem basic to the programmer/author might be sometimes difficult for an end user. For example, difficulty in tallying the calculations and coming up with exact figures. So, the objective is to bring this to attention when it appears that the visibility is less on public forums.

> 
I thought some basic respect for authors' time and their free software support decisions would be implied in this public interaction on their github repository.

Of course, completely agree on that and would like to mention that its a give and take relationship  and should come from both ends. Nobody like to disrespect or being told something without respect. Yes, the question posted was vague in the sense that it did not explained or elaborated on the requirements and should be improved. Everybody's time is precious and rather being sarcastic to each other, everybody should try to get to a solution. I really appreciate your help in this case and the answer posted on biostars.org. We do respect your time and efforts and look forward for a harmonious, respectful and fruitful interactions. 

Thanks

**Comment by surajmetha55** [comment]
:like:
