### ISSUE TITLE
prepDE.py pulls around 50% MSTRG as gene_id from Stringtie_merge RNA-Seq

### ISSUE THREAD

**Issue by ThStruk** [gpertea/stringtie#179]
Dear community,

I am running an analysis of unpaired RNA-sequencing reads (derived from mice) as my first ever bioinformatics project, and am stuck at one point. Although a few people reported similar problems regarding MSTRGs as the output of their raw gene counts tables, I couldn't solve the problem with the answers given there.

The workflow I used was STAR for the alignment. The raw fastq.gz files, which were obtained using an Illumina sequencing machine, were checked using FastQC. The resulting STAR output .bam file was used as input for stringtie, using the following commands in a linux shell (essentially following the protocol of the Nature Protocols paper from Pertea et al. published in 2016):

maindir=`pwd`; for i in $( ls -d *Mouse* ); do cd $i; echo $i; label=$i; output=$i."gtf"; stringtie -p 8 -G /RAID5/indices/STAR_mouse/Mus_musculus.GRCm38.91.gtf -e -o $output -l $label Aligned.sortedByCoord.out.bam; cd $maindir; done;

stringtie --merge -p 8 -G /RAID5/indices/STAR_mouse/Mus_musculus.GRCm38.91.gtf -e -o stringtie_merged.gtf  mergelist.txt

maindir=`pwd`; for i in $( ls -d *Mouse* );  do echo $i; cd $i; stringtie -e -B -p 8 -G $maindir/merged.annotated.gtf -o Deseq2/$i.gtf Aligned.sortedByCoord.out.bam; cd $maindir; done

The resulting .gtf-files were fed into the prep.DE.py, in order to use the resulting output raw gene counts table for further downstream analysis with DESeq2. 

python ./prepDE.py -i python_guide.txt

Here, around 50% of the genes are labled as MSTRGs in the output file although in the Stringtie-merge file there is an ENSMUSG ID in every row. Interestingly, sometimes as gene_id and sometimes as ref_gene_id. I have attached a few lines of the stringtie_merged file as a manually shortened .txt file (I just copied the first and last ~500 lines since the original file is far too large to be attached to this post). Those should illustrate my problem. Intrestingly, the Input-.gtf files for stringtie differ, with some having no MSTRG-genes, and some having a lot more (Input python example 1 and 2).

My question is: Is there any way how I can change the stringtie file, so that the python script only gives me the ENSMUSG IDs (or the gene names) as an output in the raw gene counts table? Or how should I deal with those MSTRG-labeled genes in general?

In case you need more information to help me, please let me know.

Thank you for your help,

Thaddaeus
[stringtie_merge_example.txt](https://github.com/gpertea/stringtie/files/2085016/stringtie_merge_example.txt)
[Input_python_example1.txt](https://github.com/gpertea/stringtie/files/2085107/Input_python_example1.txt)
[Input_python_example2.txt](https://github.com/gpertea/stringtie/files/2085113/Input_python_example2.txt)

**Comment by gpertea** [comment]
I know this issue frustrates many users and I am looking into practical ways to alleviate it.. As you probably figured it out, there is a simple technical reason why those MSTRG gene_ids are assigned there in StringTie output instead of the original gene_ids:  an unique gene_id was needed (internally) to identify a *locus* in StringTie, i.e. a contiguous region on the genome where transcripts overlap (their exons, more specifically), that is, a *cluster* of transcripts defined by the transitive overlap property (transitive closure). prepDE only uses the *gene_id* attribute to determine the gene ID (duh) so whatever identifier you want to see for the gene in the expression table, should be in that attribute.
We simply could not rely on the uniquenes/correctness of the reference gene_id.. Also, many times a StringTie locus is very different from the reference loci, as it comes from a mix between novel transcripts and overlapping reference transcripts, and sometimes even multiple reference genes (loci) can be merged into a larger StringTie locus due to extended overlaps between the member transcripts. The unique MSTRG solves all these ambiguities. 
To clarify one of your observations: the ENSMUSG.. *gene_id* entries you see in StringTie's output (at the end of the file) are only for the reference transcripts which had absolutely no overlap with any of the StringTie-assembled transcripts, so they are not "merged" and even considered for merging, they are just copied over from the reference annotation file, pretty much, keeping their original gene_id (because StringTie did not need to handle them internally for the merging procedure).

A user-side solution at this point would be the post-processing of the stringtie `--merge` GTF output, before running StringTie to estimate that GTF for each sample, as to adjust the gene_id in order to include somehow any other information about the genes that the user might want (using the *ref_gene_id* and/or *gene_name* of the transcripts with the same MSTRG gene_id). 
For example, if the original gene_id for a bunch of transcripts was `MSTRG.4` then that could be modified to collect *all* the ref_gene_id for those transcripts and replace the gene_id with a composite string like this: `MSTRG.4|ENSMUSG00000025903|ENSMUSG00000104217|ENSMUSG00000033813`
(this actually reflects the data from the first example file you attached above)
I wrote a quick perl script doing just that, as an example: 
https://gist.github.com/gpertea/b83f1b32435e166afa92a2d388527f4b

**Comment by gpertea** [comment]
I realized I am unclear about the source/origin of those `Input_python_example*.txt` files, how they differ from the `stringtie_merge_example.txt` .. The script I posted above might not work for those as they do not seem to have `ref_gene_id` in place, but only `ref_gene_name` sometimes..

**Comment by ThStruk** [comment]
Thank you very much for your quick and in-depth response. It really helped me to understand the reasoning behind the MSTRG-tags better. I will try to modifiy the stringtie_merge.gtf file as you suggested.

The input_python files are the output of running stringtie with the output of stringtie_merge as the reference, meaning the output of the following line of code:

maindir=pwd; for i in $( ls -d Mouse ); do echo $i; cd $i; stringtie -e -B -p 8 -G $maindir/merged.annotated.gtf -o Deseq2/$i.gtf Aligned.sortedByCoord.out.bam; cd $maindir; done

But since it is far more practical to follow your advice to change the stringtie_merge.gtf before re-running stringtie with the merge.gtf as the reference file (because I then only have to edit one file and not one file per sample) it is not a problem that the pearl script might not work with the attached input_python_example files.

**Comment by ThStruk** [comment]
Thank you very much for your help!

The perl script you provided worked just fine on the merge.gtf file. I inspected the file manually afterwards, and it seems only a relatively small number of ENSMUSG "report" to different MSTRG-identifiers, while most of the MSTRGs and ENSMUSG are 1:1 pairs, but there are many MSTRGs, that represent Transcripts from multiple ENSMUSG-loci (see sample.txt). The attempt to run stringtie with the perl-script manipulated merged.gtf was successful, meaning that I have input files for the python script in order to obtain raw gene counts for further analysis in Deseq2.

My follow up question is: How should I best process those MSTRGs after obtaining the raw gene count table (when I am not interested in novel transcripts)? My first impulse is to simply add the gene counts for identical ENSMUSGs up, discarding the MSTRG tags, before feeding the raw gene counts as input to Deseq2, So that I would have stable gene IDs for downstream analysis. Would that procedure be mathematically sound?

[sample.txt](https://github.com/gpertea/stringtie/files/2091818/sample.txt)

**Comment by gpertea** [comment]
Oh, actually if you are "not interested in novel transcripts", which are indeed complicating things (yet are the whole reason for the "full" protocol with `stringtie --merge`) then perhaps you would be better off running the "alternate", faster protocol, as mentioned in issue #170 and in StringTie's manual web page?
That way you could directly get expression estimates (read counts) for all those ENSMUSG genes separately, for each sample -- by simply using the reference annotation file instead of the merged GTF produced by `stringtie --merge`. I somehow assumed you knew that was an option..

**Comment by ThStruk** [comment]
Thank you very much for your help! I will try the shortened protocol. My apologies that I somehow must have overlooked that solution.

**Comment by NDUFB11** [comment]
Hello everyone, 
After running that script I still can't associate the gene_id to the transcripts.
Do you have any advice to see what am I doing wrong? 

thank you
