### ISSUE TITLE
Strange Stringtie Error!!!

### ISSUE THREAD

**Issue by amoltej** [gpertea/stringtie#196]
Hi, I have used SRA generated fastq files for mapping using STAR aligner. Even though the default bam file is sorted by coordinates, stringtie reporting error "Error: the input alignment file is not sorted!"

I tried to sort BAM file again using samtools but the result is same. 
I also tried using different options from fastq-dump like " -I for Append read id after spot id as 'accession.spot.readid' on defline" and "-F for Defline contains only original sequence name." and created new fastq files and tried creating new BAM file. But the result is still same. 
When I am using RNA seq fastq files created by ART (simulator) it works fine.

Can you please help me to sort this issue. 
Thanks in advance.

**Comment by gpertea** [comment]
I haven't run into this error before for BAM files which were actually sorted with samtools (and aligned with proper options by HISAT2 or STAR). I guess it's possible to have encountered an edge case there that is considered ordered properly by samtools but StringTie somehow misreads it as out of order.. What options are you using for the stringtie run, are you excluding any chromosomes?

Is it possible for me to have a look at that BAM file (or a smaller subset of it that still triggers that error)? It would be great if I can debug it when that error happens and check it against the actual composition of the BAM file to see what's throwing off stringtie there..

**Comment by amoltej** [comment]
Thanks for reply, 
I have attached two bam files. Aligned.sortedByCoord.out.bam is a bam file generated by STAR and sorted by STAR aligner. 
The second file is Aligned.sortedByCoord.out_sorted.bam is a bam file generated by STAR but also sorted by `samtools sort`.

I suspected that the naming pattern of my genome scaffold could be creating problem hence I changed the names and tried it again but it didn't work. So you may find difference in the scaffold names in both bam files.

I am not also using any special option with stringtie. my command is 
`stringtie -o out.gtf Aligned.sortedByCoord.out.bam`

[Aligned.sortedByCoord.out_sorted.zip](https://github.com/gpertea/stringtie/files/2347891/Aligned.sortedByCoord.out_sorted.zip)

**Comment by gpertea** [comment]
After taking a closer look at your data, it looks like the problem here is that your reference sequences file had a lot of duplicated entries (most of those Znev_* reference sequences were present twice in the SAM header and duplicated alignments in the sorted SAM file at different locations in the file). This was probably a mistake in your protocol/pipeline which should be enough to explain the confusion here, but what baffles me is that `samtools sort` does *not* eliminate this confusion, instead it silently accepts the duplicate entries in the SAM header and sorts the whole file just based on that order, keeping the duplicates in place -- and also somehow keeping the read alignments separately for each instance of the same reference sequence - since the duplicated alignments are actually marked as "secondary" by STAR, somehow they get assigned by 'samtools sort' to the 2nd instance of the same reference sequence (!).
STAR did not seem to care about the duplicate reference sequences either.. (which might be something you might want to report to the STAR developers, I don't see why that would be allowed in the first place, allowing this nonsense to propagate through `samtools sort` etc. I guess most programs would not expect someone to use *duplicated* reference sequences..

StringTie sanely assumes that each reference sequence has an unique name and if it encounters *again*  alignments to the same reference sequence [name] it will throw that error you encountered, which is correct (in my opinion).
