### ISSUE TITLE
identification of novel exons from human alignment data

### ISSUE THREAD

**Issue by kokonech** [gpertea/stringtie#197]
Hi!

I am interested to find novel transcripts structure from human RNA-seq data. Is StringTie suitable for this?

Basically, from BAM file it’s easy to observe that there is a novel unannotated exon in a gene, split reads support its connection to other known exons and I would like to have detailed coordinates of it. 

However, running StringTie result leads to result having only 1 exon (simply exon_number “1”) for each gene of the same size as the transcript (independent of running with or without annotation). 
In a specific region of interest only single transcript is reported. 

Here’s the example command:

TOOL=~/tools/stringtie-1.3.0.Linux_x86_64/stringtie
ANNOTATION=gencode.v19.annotation.clean.gtf
$TOOL -G $ANNOTATION -p 8 -o $RESDIR/${PID}_StringTie_gencode19.gtf $FILE

Did I miss some parameters? What could be the issue?

**Comment by gpertea** [comment]
Yes, StringTie should be a good tool for finding novel structures. In this particular case it is possible that some information might be missing from the BAM file and that prevents StringTie from "seeing" that isoform that you seem to be sure it's there (how exactly was that "easy to see" for you, presumably with a viewer like IGV?). A couple of comments/questions to clarify here:

- version 1.3.0 of stringtie is a bit old and might have some bugs/issues that were fixed in the most recent version available on our website
- how were the **read alignments** performed? (which aligner, what options?); finding novel transcript structures relies on the presence of the XS tag in the BAM file, as generated by the aligner 
- stringtie will ignore spliced read alignments which do not have the XS tag assigned; for most aligners this means that only canonical splice sites can contribute to novel isoform detection in StringTie

**Comment by kokonech** [comment]
Hi! Thanks a lot for quick reply! 
Yes, the exons were observed from IGV and also supported from chimeric transcript discovery tools (but only the breakpoint positions, not full exon structure).
Importantly, the alignment was performed previously with STAR. In my case it might be a bit problematic to re-run alignment on these data with TopHat or HISAT. Is this the only solution? Or is there a way to adjust already produced alignment BAM files?

**Comment by gpertea** [comment]
I recall STAR also had an option to add those XS tags (the `--outSAMstrandField intronMotif` or something like that) -- do you know if that was used? 
While it is theoretically possible to "annotate" the existing alignments by checking the genome sequence for the splice sites and add the missing XS tags (if they were indeed missing), but since there might not be any tool already available for doing this, perhaps instead of developing one it might be more expedient to use something like `samtools fastq` (which involves a `samtools sort -n` before), and re-run the alignments  with HISAT2 or STAR using the correct options to generate the XS tags.
I would first clarify if those are indeed canonical splice sites observed there.. otherwise all this effort might be in vain. If that region already has some known transcripts exon-overlapping some of the those novel spliced alignments, that might be enough for stringtie to infer the transcript strand for those spliced alignments, even without the XS tag (but looking at the current code, that might require a slight adjustment of StringTie to do that -- but I think I can do that quickly if that's the case).

Ah, important note -- I remember that older versions of stringtie had a problem reading some of the older Gencode GTFs (and v19 might be one of those) as it would wrongly consider the whole gene span to be a single exon transcript in some cases, and it would be terrible if this were the case here..
So I have to push again for giving a try to the most recent version of stringtie instead of the old and potentially buggy/lacking v1.3.0 that you have there..

And, as I mentioned above, if there is a known gene in that region already I could quickly adjust StringTie to assign the transcript strand for spliced alignments based on overlaps with other known transcripts (without the need for the XS tag, that is). But you should be willing to give this new version of StringTie a try, instead of that old v1.3.0..

**Comment by kokonech** [comment]
Thanks a lot for detailed update! I rerun the alignment using HISAT2 and afterwards applied StringTie version 1.3.4d. In result it was possible to detect novel exons confirming previous observation. Issue can be closed ;)

**Comment by gpertea** [comment]
Thank you for following up on this, I am glad it worked out.
