### ISSUE TITLE
Disreprency in counts between MSTRG genes and nonMSTRG genes

### ISSUE THREAD

**Issue by Xalyonders** [gpertea/stringtie#206]
After running stringtie according to the instructions on the website and then running prepDE to summarize the samples I was surprised at a detail from the result. The majority (95%) of counts are in the MSTRG genes rather than the genes from the annotation. This can't be right. Why is this? Attached is a report of total gene counts across the gene count matrix for MSTRgs and ENSGs.  Below is the code for stringtie and prepDE minus the for loops across samples. Note this is not caused by annotation error.
First step:
"""
bam=$1
outdir=${bam%%.bam}
mkdir $outdir
stringtie -p 8 -G Homo_sapiens.GRCh37.75.gtf -o ./${outdir}/transcripts.gtf $bam
"""
merge step:
"""
stringtie --merge -p 8 -G Homo_sapiens.GRCh37.75.gtf -o stringtie_merged.gtf ./*/transcripts.gtf
"""
Quantification step:
"""
bam=$1
outdir=${bam%%.bam}
stringtie -e -B -p 8 -G stringtie_merged.gtf -o ./${outdir}/expression.gtf $bam
"""
prepDE
"""
python prepDE.py -i ./ -l 75
"""
[Sum of counts across samples.txt](https://github.com/gpertea/stringtie/files/2548084/Sum.of.counts.across.samples.txt)

**Comment by gpertea** [comment]
How are you counting those 95% gene IDs exactly? MSTRGs are automatically assigned as gene_ids for almost the entire output of `stringtie --merge` anyway, specifically for every locus which has at least one assembled stringtie transcript (STRG.#.#). The other 5% gene_ids you see there as ENSGs are probably those which did not have any overlap with any assembled transcripts -- because those are simply copied over to the output without getting a MSTRG assigned.
Perhaps you'd want to look at the value of `ref_gene_id`attribute instead, if present for those MSTRGs - that should encode the original gene_id for the MSTRG transcripts that fully match at least one of the reference transcripts for that gene_id.

There are some details discussed in issues #159 and #179, perhaps they may help clarify how these MSTRGs are assigned and provide a possible workaround etc.

**Comment by Xalyonders** [comment]
By pandas sum function in python. Thanks for the quick response I had clearly missunderstod how the annotation worked. The issue 179 answers my question exactly.
