### ISSUE TITLE
Trouble installing stringtie2

### ISSUE THREAD

**Issue by NatPRoach** [gpertea/stringtie#226]
Hello, I'm having some trouble installing stringtie2. I'm installing on a MacBook Pro running OS X El Capitan v 10.11.16
When I run `make release` as instructed in the README, it throws an error after the following line: `c++ -g -O0 -gdwarf-3 -DDEBUG -D_DEBUG -DGDEBUG -Wall -Wextra -I. -I./gclib -I./samtools-0.1.18 -fsigned-char -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -std=c++0x -fno-strict-aliasing -fno-exceptions -fno-rtti -c rlink.cpp -o rlink.o` 

The error message it throws is the following:
```
rlink.cpp:13092:21: error: variable length array of non-POD element type 'GVec<int>'
        GVec<int> bettercov[npred];
                           ^
```

As a sanity check I tried installing stringtie1, and didn't run in to any troubles.

I'd appreciate any help you can provide.

**Comment by gpertea** [comment]
Indeed, that was a C++ non-compliance issue that we didn't catch during our mostly-Linux testing (GCC was quite forgiving about that). I added a quick patch which hopefully fixed this problem. Could you pull this updated version and build it again and please let me know if the problem is fixed?  Thank you.

**Comment by NatPRoach** [comment]
That seems to have fixed it. Thanks!
