### ISSUE TITLE
Question:Appropriate Star-mapping options

### ISSUE THREAD

**Issue by Tdanis** [gpertea/stringtie#265]
Hello, 

Because I am new in bioinformatics could you suggest me please the suitable options in Star mapper in order the outfile be compatible with StringTie.

Thank you very much

**Comment by gpertea** [comment]
Star is a great mapper but we (the developers) have no direct experience with it for StringTie (we use HISAT2) so we cannot answer your question without looking into the Star manual at this time -- which you could very likely do yourself, no? 

As a generic hint, whatever read aligner you use, if its documentation mentions options that make the output more suitable for _Cufflinks_ transcript assembly, those would also apply to StringTie, since StringTie has the same alignment data requirements like Cufflinks.

You may also find a wider community that might be able to answer this kind of questions in public forums like Biostars, SEQanswers etc.
