### ISSUE TITLE
segmentation fault with 2.1.2

### ISSUE THREAD

**Issue by dputhier** [gpertea/stringtie#285]
Hello,
I am getting a segmentation fault with version 2.1.2 when processing long reads from Nanopore. Downgrading to version 2.1.1 fixed the issue.
Best

Dataset:

            http://s3.amazonaws.com/nanopore-human-wgs/rna/bamFiles/NA12878-DirectRNA.pass.dedup.NoU.fastq.hg38.minimap2.sorted.bam

Command:

         # Leads to segmentation fault using version 2.1.2 (not with 2.1.1)
        stringtie -v  -L -p 8 -o GM12878_2.gtf NA12878-DirectRNA.pass.dedup.NoU.fastq.hg38.minimap2.sorted.bam

System Info:

          ProductName:	Mac OS X
          ProductVersion:	10.15.1
          BuildVersion:	19B2093

Also tested under WSL:
System Info:

         Ubuntu 20.04 LTS

**Comment by gpertea** [comment]
Thank you for the report. I was able to test your data on the current version (v2.1.3b) and it seems to work OK. So this seems to be one of the cases that were fixed between v2.1.2 and v2.1.3.

Is there any reason to not _upgrade_ to the latest version instead of _downgrading_ to v2.1.1 for your data?  I'm pretty sure v2.1.1 had some other bugs that might cause crashes on other data.

**Comment by dputhier** [comment]
I downgraded because conda does not offer currently version v2.1.3.
Best
