### ISSUE TITLE
Stringtie -merge Segmentation fault

### ISSUE THREAD

**Issue by njbernstein** [gpertea/stringtie#37]
I'm trying to run -merge however I get a `segmentation fault` error every time. The line of code is:

`nohup /labshare/Nick/tools/stringtie-1.2.0.Linux_x86_64/stringtie --merge /labseq/analysis_results/projects/"$PROJDIR"/"$PROJNAME"/gtf.list  -G /labseq/Genomes/rsem/hg19.gtf -o /labseq/analysis_results/projects/"$PROJDIR"/"$PROJNAME"/"$PROJNAME".run1.annotation.gtf  -v  > /labseq/analysis_results/projects/"$PROJDIR"/"$PROJNAME"/log/"$PROJDIR"."$PROJNAME".merge.log &`

Please let me know what info will help you help me in this process.

The run1 ran perfectly smoothly, and merge has run when I use  a small subset (6 samples) of my cohort (311 samples).

The samples were aligned with 2-pass STAR alignment. Any help would be much appreciated.

Best

**Comment by gpertea** [comment]
Sorry for the unfriendly crash. How many samples are in that gtf.list (311) ?
It would be good to check if all of those file are actually there and non-zero length, and I always recommend to use full paths to the gtf files there. 

Could you please try running  v1.2.1 instead of the v1.2.0 which you appear to be running, hopefully you should get a more informative error message when it fails there, as I remember adding a bit more checking code when processing that file list since v1.2.0, specifically for situations where some of the files in the list might be missing or zero-length, or if there are empty lines in that file etc. (actually with v1.2.0 I think it would crash if there was any empty line in that file).

**Comment by njbernstein** [comment]
Just checked the paths and file lengths. They all seem to be good. I'll try running with 1.2.1 and let you know

**Comment by njbernstein** [comment]
So now it seems the merge is sucking up tons of memory ~ 148110352 kb with the following call

`nohup /labshare/Nick/tools/stringtie-1.2.1.Linux_x86_64/stringtie --merge /labseq/analysis_results/projects/"$PROJDIR"/"$PROJNAME"/gtf.list -G /labseq/Genomes/rsem/hg19.gtf -o /labseq/analysis_results/projects/"$PROJDIR"/"$PROJNAME"/"$PROJNAME".run1.annotation.gtf -v > /labseq/analysis_results/projects/"$PROJDIR"/"$PROJNAME"/log/"$PROJDIR"."$PROJNAME".merge.log &`

Any ideas?

**Comment by gpertea** [comment]
148GB RAM for a merge, this is unusual indeed. How many files are listed in gtf.list?
I am afraid the only way to look into this properly is to get those gtf files to us (at least some of them) to get an idea about what's so unusual about these data..

**Comment by njbernstein** [comment]
311 files. I'll see if I can get some of those to you. If i can what would be the best mode for you to get them through? dropbox or something like that?

**Comment by gpertea** [comment]
It would be great if you could pack many of those files (all would be best, they should compress well) and upload the archive to our FTP server - please drop me a note at gpertea@jhu.edu so I can send you FTP upload instructions when you're ready to upload that compressed archive.

**Comment by njbernstein** [comment]
Alright. I'll let you know shortly If I am able to send the files. Thanks so much for your help thus far.

**Comment by gpertea** [comment]
Issue was fixed in v1.2.2.
