### ISSUE TITLE
segmentation fault when using annotation file with --merge

### ISSUE THREAD

**Issue by jjenny** [gpertea/stringtie#42]
Hello,

I downloaded the gtf file from UCSC hg19 knownGene table and tried to use with the -G option when merging gtfs.  I get a segmentation fault and the last few lines before stringtie exits are:

[03/10 12:03:30]>bundle chr14:105992953-107283085(273) (38 guides) loaded, begins processing...
Segmentation fault (core dumped)

The merging option works fine without a reference annotation file.

Thanks,

Jenny

**Comment by gpertea** [comment]
Thank you for reporting this, we should take a closer look and get more information. I am assuming you are running v1.2.2 (as there were some potential memory issues when merging with older versions). Could you please let us know:
 * how many GTFs you are trying to merge?
 * how much RAM you have on that computer?
 * if you can see the core file, what is its size?

The best way to get to the root of the problem would be to get those input files to us so we can investigate this locally.. After a crash during merge there should be a temporary directory with a bunch of .bam files in there -- ideally we would like to get those .bam files so we can debug this locally here (no need for the original transcript files).
In order to limit the data transfer you could extract the region chr14:105992953-107283085 from all those .bam files and send those resulting smaller .bam files to us instead (after making sure there is no other bundle being processed there which might have caused the crash -- which could be the case if you ran with -p option and >1 CPUS..). 
Please shoot me an e-mail at gpertea@jhu.edu to discuss more of these details and hopefully arrange a data transfer.

**Comment by gpertea** [comment]
After further investigation this was found to be a case of limited stack size per thread on some systems, which causes a crash when recursion during graph traversals gets very deep. 
After using  `pthread_attr_getstacksize()` we found out that all our Linux systems have at least 8MB default thread stack size (10MB on our larger memory servers), while Mac OS X desktops only have 512KB (!). Jenny's systems have a 2MB default stack size which apparently is not enough for some of the deep graph traversals in StringTie.

This issue was fixed in the source tree by checking the current stack size and increasing it to 8MB if found to be lower than that (using `pthread_attr_setstacksize()`). This makes the program run successfully on Jenny's systems and also on Mac OS X computers. The fix is now only available in git here but it will be included in the next public release (v1.2.3).

The solution proposed by @infphilo in the [HISAT2 branch](/gpertea/stringtie/tree/HISAT2) is the best approach to this problem in terms of engineering, but it involves the additional error-prone work of converting all such recursive calls to iterative while lowering code readability & maintainability.
