### ISSUE TITLE
minimum read coverage by exons instead of transcript (-c)

### ISSUE THREAD

**Issue by gdoura** [gpertea/stringtie#43]
I'm writing to know if you could set a parameter that would filter out exons that do not pass a threshold of minimum read coverage, because I have an example of a transcript that has an extra exon with a coverage of only 3 while all the other exons have at least 80 reads. Also sometimes exons are too long 
maybe an option maybe added to limit the extent of the exons. This would facilitate the study of differential alternative splicing. 

best regards.

**Comment by mpertea** [comment]
We do not have such a parameter right now. I will consider introducing one in the future but this does not have an easy and straight forward solution, since coverages are not uniform across the transcripts, and can have sudden drops as our experience with some rna-seq data sets and some recent studies have shown. Even filtering out regions with coverage less than a given threshold might introduce gaps, fragmentation and false positives as the coverage might drop below the threshold and then go back up to just above that. Post filtering the assembled transcripts might be easier.

**Comment by gdoura** [comment]
thank you very much for your clear answer! 
best regards

**Comment by gdoura** [comment]
Dear Dr Pertea, 
Could you please explain (an example  will be greatly appreciated! ) how to do the post filtering of the assembled transcripts based on coverage?

Thank you very much in advance.

Best regards.
