### ISSUE TITLE
exon length is ZERO!

### ISSUE THREAD

**Issue by yji1983** [gpertea/stringtie#47]
Hi, guys

Did you ever notice that in StringTie's gtf lengths of some exons were equal to 0?

**Comment by gpertea** [comment]
No -- could you provide an example output line please? I'm assuming such exons are not given as reference annotation to StringTie..

**Comment by yji1983** [comment]
1       StringTie       exon    22175136        22175287        1000    -       .       gene_id "MSTRG.391"; transcript_id "MSTRG.391.8"; exon_number "21";
1       StringTie       exon    22175386        22175524        1000    -       .       gene_id "MSTRG.391"; transcript_id "MSTRG.391.8"; exon_number "22";
1       StringTie       exon    22176534        22176685        1000    -       .       gene_id "MSTRG.391"; transcript_id "MSTRG.391.8"; exon_number "23";
1       StringTie       exon    22176856        22176991        1000    -       .       gene_id "MSTRG.391"; transcript_id "MSTRG.391.8"; exon_number "24";
1       StringTie       exon    22178039        22178083        1000    -       .       gene_id "MSTRG.391"; transcript_id "MSTRG.391.8"; exon_number "25";
1       StringTie       exon    22179457        22179563        1000    -       .       gene_id "MSTRG.391"; transcript_id "MSTRG.391.8"; exon_number "26";
1       StringTie       exon    **22180301        22180301**        1000    -       .       gene_id "MSTRG.391"; transcript_id "MSTRG.391.8"; exon_number "27";

**Comment by gpertea** [comment]
That's length 1 (not 0), which is theoretically possible (microexon) but could also be an artifact caused by spurious alignments. 
I couldn't tell -- is that the last exon of that transcript ? Also, what was the aligner used?
It would be very helpful if you could provide us with the .BAM alignments in that region - is that a possibility? Also, if any reference annotation was used, I am curious if there was a micro-exon annotated at that coordinate already..
Thank you!
