### ISSUE TITLE
gene id from reference GTF not shown in the output file

### ISSUE THREAD

**Issue by sahyoun** [gpertea/stringtie#5]
Hi,

I'm using StringTie and it runs smoothly and quite fast on my data, however, when I look at the output file I don't see the gene_ids that were in the GTF file, instead I see the following pattern:

.... gene_id "samplename.1"; ...
.... gene_id "samplename.2"; ...
.... gene_id "samplename.3"; ...
etc etc

Only the reference id is found the same where I can actually look up the gene_id in the GTF file and then search for it in the StringTie output. But this is not useful since I would like to have a look at the FPKM before proceeding in the differential analysis.

I'm using the following command line to run StringTie:

stringtie sample1.sorted.bam -e -p 4 -G GTF/dm3_transcriptome_annotation.gtf -l sample1 -o sample1

**Comment by gpertea** [comment]
Indeed, currently StringTie only shows the matching reference transcripts in the *reference_id* attribute of the output GTF. It seems that you'd like to see some recognizable gene IDs or gene names from the annotation - in other words, to have StringTie better "annotate" its own output.. This is a valid suggestion and we would consider adding this in a future version. We hesitated adding this because it could get complicated for those assemblies which may span multiple gene regions, but for those which match exactly the reference transcripts (hence the reference_id), indeed it is very easy to add the gene_name and/or gene_id attributes as well - I'll add these in the next version, likely as a new *ref_gene_id* attribute, I hope this would help? 
Unfortunately I cannot assume that the annotation file would even have *gene_id* attributes, if it's a NCBI GFF3 or another annotation source, what you call "gene_id" in your case, could be called differently in other files. Transcript ID (called "ID" in GFF3) is the most stable identifier that we can expect to find in the reference annotation file, that's why we've only provided that reference ID.

Meanwhile you can probably use other programs or scripts which could quickly annotate StringTie transcripts based on another GTF/GFF file (e.g. cuffcompare or gffread from the Cufflinks suite), though probably in your case, the way you are doing it now (looking up the reference_id back in the annotation) is still the easiest way, it just needs to be scripted somehow.

**Comment by sahyoun** [comment]
The idea is that when using cufflinks, the gene ids that are found in 
the reference transcriptome GTF are annotated in the cufflinks output 
files so I was able to grep easily for them since I'm expecting to see a 
down regulation of these genes in case of KD or so. I'm not sure how is 
this done in cufflinks, but sure it is more convenient than needing to 
look for the reference id.



On 3/27/15 4:42 AM, Geo Pertea wrote:
>
> Indeed, currently StringTie only shows the matching reference 
> transcripts in the /reference_id/ attribute of the output GTF. It 
> seems that you'd like to see some recognizable gene IDs or gene names 
> from the annotation - in other words, to have StringTie better 
> "annotate" its own output.. This is a valid suggestion and we would 
> consider adding this in a future version. We hesitated adding this 
> because it could get complicated for those assemblies which may span 
> multiple gene regions, but for those which match exactly the reference 
> transcripts (hence the reference_id), indeed it is very easy to add 
> the gene_name and/or gene_id attributes as well - I'll add these in 
> the next version, likely as a new /ref_gene_id/ attribute, I hope this 
> would help?
> Unfortunately I cannot assume that the annotation file would even have 
> /gene_id/ attributes, if it's a NCBI GFF3 or another annotation 
> source, what you call "gene_id" in your case, could be called 
> differently in other files. Transcript ID (called "ID" in GFF3) is the 
> most stable identifier that we can expect to find in the reference 
> annotation file, that's why we've only provided that reference ID.
>
> Meanwhile you can probably use other programs or scripts which could 
> quickly annotate StringTie transcripts based on another GTF/GFF file 
> (e.g. cuffcompare or gffread from the Cufflinks suite), though 
> probably in your case, the way you are doing it now (looking up the 
> reference_id back in the annotation) is still the easiest way, it just 
> needs to be scripted somehow.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/gpertea/stringtie/issues/5#issuecomment-86807587>.
>

-- 
Dr. Abdullah H. Sahyoun
Computational Biologist
Chromatin Regulation/Bioinformatics and Deep Sequencing Unit
Max Planck Institute of Immunbiology and Epigenetics
Stübeweg 51, D-79108 Freiburg, Germany
Tel.: +49 761 5108 707
