### ISSUE TITLE
Error at GBitVec: index 25 out of bounds

### ISSUE THREAD

**Issue by tianfree** [gpertea/stringtie#50]
When I used stringtie v 1.2.3, I got:

Error at GBitVec: index 25 out of bounds (size 25)
*** glibc detected *** stringtie: double free or corruption (!prev): 0x0000000001caccb0 ***

The input is from Hista (-dta)

stringtie mpout/Gallus_gallus/GSM752558/hisat2_sorted.bam -p 4 -G $tdir/${spp}.gtf -l $spp -o stoutENS/Gallus_gallus/GSM752558/stringtie.gtf -A stoutENS/Gallus_gallus/GSM752558/gene_abund.tab -B

**Comment by gpertea** [comment]
Indeed after the 1.2.3 release there was another fix for this error which did not make it in the official release. The fix is in the master branch, I just tagged it as 1.2.3b and you can also get the source and Linux binary packages here:

http://ccb.jhu.edu/software/stringtie/dl/stringtie-1.2.3b.tar.gz
http://ccb.jhu.edu/software/stringtie/dl/stringtie-1.2.3b.Linux_x86_64.tar.gz

Could you please try this patched version and let me know if you still get the error ?

**Comment by tianfree** [comment]
The 1.2.3b worked well.
