### ISSUE TITLE
Is it advised to use "stringtie --merge" to use as input transcripts from multiple assemblers? If so, what is the recommended protocol?

### ISSUE THREAD

**Issue by lucventurini** [gpertea/stringtie#53]
My question regards eg the case where one has produced different sets of assemblies from eg SpliceBox/CLASS, Cufflinks, Stringtie and Trinity, and wants to merge them into a single GTF. Stringtie-merge is definitely capable of performing the operation, but the documentation is unclear on how it uses the expression information and from whence it derives it.
How should it be done correctly, given that eg Trinity transcripts aligned with GMAP do not have any expression information per se?

**Comment by mpertea** [comment]
This is an interesting question and I would like to provide an answer to it in the future versions of StringTie. As it is written right now, stringtie --merge was designed to assemble stringtie's output. It will work with assemblies from the **same** assembler that will produce at least one of the cov, FPKM, or TPM measures produced by StringTie in its gtf output. StringTie uses these measures as weights for the expressed transcripts when merging transcripts. 
The only way that might be possible to deal with stringtie --merge now when combining assemblies from different programs would be to artificially add these flags to the transcripts in the gtf file. Keep in mind that the preference used by StringTie for the weighting is TPM, FPKM, and then cov, in this order. This means that if stringtie assemblies (or some of the input files) have the  TPM measure present, when merging with transcripts from the other assemblies it will look for the TPM flag and if this is not present those transcripts will have a negative weight. You should add a value equal to at least the TPM threshold you would like to use (the default is 1 for stringtie). This is not a perfect solution because there will be a clear bias towards the transcripts produced by StringTie that have a TPM value bigger than the threshold. You might want to use a smarter way to generate the TPMs for the assemblies that lack this measure (for instance compute it yourself from the coverage produced by other programs).

**Comment by lucventurini** [comment]
Would calculating the expression with Stringtie, and then attaching the values to the GTF, be a possible option? It is something we are going to try soon.

**Comment by mpertea** [comment]
yes, evaluating expression with StringTie (and -e option) would be a good way to do it.

**Comment by lucventurini** [comment]
Good. I am doing it at the moment, and I will be curious to see the results!

**Comment by lucventurini** [comment]
On my dataset in Arabidopsis, using a GTF with abundance estimation faired considerably *worse* than without. In particular, the number of intron chains recovered in the stringtie-merged with abundance estimation vs. stringtie-merged without abundance estimation dropped by 25%, and the number of fragments (either completely or at least partly contained in a reference transcript) quadrupled - all in the context of a general drop of ~50% in the number of transcripts. Precision in general increased, but at a huge cost in term of recall.

**Comment by mpertea** [comment]
This result is actually not surprising to me. What this shows to me is that the other assembles introduce a lot of noise that was mostly discarded before when there were no estimations. This is a more complex problem and I don't think it can be solved by a simple merge like the one provided by StringTie, which was designed to merge assemblies of the same quality. When merging assemblies of different qualities they should be weighted according to their accuracies.  Also please keep in mind that the estimation mode of StringTie was designed for the very accurate annotations of known transcripts. This means that there is no guarantee that a false transcript won't get a high estimation level, and therefore just as much of a weight as a true one in the merge mode.

**Comment by lucventurini** [comment]
Great, thank you for your clarification.
