### ISSUE TITLE
One StringTie internal gene id corresponding to more ref_gene_id

### ISSUE THREAD

**Issue by biosyssun** [gpertea/stringtie#54]
Hi, Authors,

The StringTie is a great tool, but there is an inconvenience, that is some StringTie internal gene id will corresponds to more than one ref_gene_ids.  The example is as follows:

**17	StringTie	transcript	37004118	37009975	1000	-	.	gene_id "hsa.13095"; transcript_id "ENST00000394332"; gene_name "RPL23"; ref_gene_id "ENSG00000125691";
17	StringTie	exon	37007777	37007912	1000	-	.	gene_id "hsa.13095"; transcript_id "ENST00000516890"; exon_number "1"; gene_name "SNORA21"; ref_gene_id "ENSG00000252699";**

Because downstream analysis will be based on official ref_gene_id, StringTie internal gene id with more ref_gene_ids will make confused. Thus, could you provide an change to clearly quantify the expression of ref_gene?

Thanks!

**Comment by mpertea** [comment]
A locus shared by multiple transcripts gets the same gene id in StringTie. Those reference genes you mention share the same locus. This is why we provide the ref_gene_is in our output so the interested user can separate the transcripts of interest based on these labels.

**Comment by biosyssun** [comment]
Thanks for reply.
In my opinion, it will be very useful to provide an OPTION in StringTie, allowing user to decide one gene id or multiple gene id for A locus shared by multiple transcripts.
Could you provide this function in the future version of StringTie?
Thanks again.

**Comment by gpertea** [comment]
Unfortunately this would go against the definition of a locus/gene ID within StringTie, which assigns the same gene ID to all exon-overlapping transcripts on the same strand. Occasionally this may lead to the apparent merging of multiple reference genes.. In your example one of the reference genes happens to be a small nucleolar RNA which is within an intron of another gene, but due to that intron being also retained (!), the snoRNA gene got "swallowed" by the encompassing gene. Thus it is very unlikely to be able to separate the two genes in the expression estimates anyway..
