### ISSUE TITLE
values differ in gtf file and gene abundance output

### ISSUE THREAD

**Issue by jeff-sc-chu** [gpertea/stringtie#63]
Hi,

I'm using Stringtie 1.2.4 with the following command:
stringtie SRR.bam -o assembly.gtf -p 8 -G gencode.v25.annotation.gff3 -B -A gene_abundance.out -C coverage.out

Looking at the gtf file and the abundance output shows different values for FPKM and TPM. I paste the first five gene_id from each file below:
gtf:
===
chr1    StringTie       transcript      36534   36849   1000    .       .       gene_id "STRG.1"; transcript_id "STRG.1.1"; cov "19.614035"; FPKM "6.688056"; TPM "10.944590";
chr1    StringTie       transcript      35245   36073   1000    -       .       gene_id "STRG.2"; transcript_id "STRG.2.1"; reference_id "ENST00000461467.1"; ref_gene_id "ENSG00000237613.2"; ref_gene_name "FAM138A"; cov "0.327684"; FPKM "0.111735"; TPM "0.182847";
chr1    StringTie       transcript      52473   53312   1000    +       .       gene_id "STRG.3"; transcript_id "STRG.3.1"; reference_id "ENST00000606857.1"; ref_gene_id "ENSG00000268020.3"; ref_gene_name "OR4G4P"; cov "0.119048"; FPKM "0.040593"; TPM "0.066429";
chr1    StringTie       transcript      137682  137965  1000    -       .       gene_id "STRG.4"; transcript_id "STRG.4.1"; reference_id "ENST00000595919.1"; ref_gene_id "ENSG00000269981.1"; ref_gene_name "RP11-34P13.16"; cov "0.000000"; FPKM "0.000000"; TPM "0.000000";
chr1    StringTie       transcript      139283  139642  1000    .       .       gene_id "STRG.5"; transcript_id "STRG.5.1"; cov "3.111111"; FPKM "1.060837"; TPM "1.735993";

Gene abundance output:
====================
Gene ID Gene Name       Reference       Strand  Start   End     Coverage        FPKM    TPM
STRG.1  -       chr1    .       36534   36849   19.611408       12.973087       21.229654
STRG.2  -       chr1    -       34554   36081   0.371342        0.184276        0.301557
STRG.3  -       chr1    +       52473   53312   0.118452        0.040593        0.066429
STRG.4  -       chr1    -       137682  137965  0.123239        0.042022        0.068767
STRG.5  -       chr1    .       139283  139642  3.108336        2.111887        3.455972

For the first 5 gene_id, with the exception of STRG.3, all other show different values for Coverage, FPKM and TPM. 

Could you explain the difference here and which value is the accurate calculation?

Best,

**Comment by mpertea** [comment]
Thank you for bringing this to our attention! 

While we expect to see some variations among the measures of transcripts and genes, this showed us there was also a  bug in the computation of the measures computed for unstranded genes (in this case STRG.1, and STRG.5). We fixed this bug and we will release a new version of StringTie (version 1.3.0) soon. 

Measures for genes STRG.2, STRG.3, and STRG.4 are correct. The reason why their measures differ from the transcripts assembled in the region is due to the fact that for a gene we measure ALL reads that map to the gene's locus (including the reads that were not able to be assembled into transcripts due to too low coverages), i.e. the gene abundance shows all the activity in a specific locus. 

We provide the gene abundance file so one can choose whichever measure they like best: the one in the gene abundance output, or the sum of all measures of the transcripts expressed in a locus. Keep in mind that if you choose the later case (which is the usual approach), that might not show all the activity for a specific gene.

**Comment by jeff-sc-chu** [comment]
got it. thanks!
Glad I can help. 
It's a great tool.
