### ISSUE TITLE
what exactly is the "-e" option doing? 

### ISSUE THREAD

**Issue by rdbcasillas** [gpertea/stringtie#67]
As it says in the documentation, "-e" option will not provide any novel transcripts and reads with no reference transcripts will be entirely skipped. So I ran Stringtie with and without -e option and I noticed something discomforting. Some of the genes with high coverage and FPKM values are being skipped without -e option but show correct high coverage info with -e option. I thought the only side-effect of removing -e option is that reads with _**no**_ reference transcript will be removed. Is it because of the following:

> Note that if option -e is not used the reference transcripts need to be fully covered by reads in order to be included in StringTie's output. 

If yes, can we change the percentage of coverage that is sufficient when not using "-e" option? Because otherwise, essential high coverage and high FPKM genes are being missed without the "-e" option.

**Comment by gpertea** [comment]
I think this might just a transcript naming confusion and also the issue of "real data" vs "reference annotation". **Without -e** StringTie assigns the reference transcript ID only to those assembled transcripts which perfectly match the reference transcript (i.e. the same exact intron chain). However if, say, in a sample there is insufficient data (read coverage) for StringTie to perfectly reconstruct a reference transcript, or if it assembles an isoform which is close, but not identical to a reference transcript (i.e. a potentially "novel" isoform which might be missing from the reference annotation), StringTie will just assign its own transcript IDs to it (with a *STRG* prefix by default) without referring the reference transcript.

However, **with -e**, StringTie does not only discard those reads which do not overlap any reference transcripts, but also does not attempt to perform its own evidence-driven assembly of the read alignments which do overlap reference transcripts. Instead, many of the reads that in the cases described above (without -e) were assembled into slightly different (or partial) transfrags, are now somewhat constrained to be simply mapped on to the given reference transcripts, even though such reads might not fully cover or virtually be able to reconstruct those reference transcripts -- so reads are simply mapped and counted as "coverage" (albeit imperfect/incomplete) of the given reference transcripts.

So the answer to your last question is no -- because the native mode of operation of StringTie (without -e) is alignment driven, i.e. reconstructing the most likely transcripts from the given read alignments, no matter what the reference annotation suggests (as that may be incomplete or even incorrect..). The high coverage transcripts are not missed without -e, they are still represented in the output (be it partially or with a slightly different structure) but with different names, as the assemblies generated by StringTie for those loci might not perfectly match a reference transcript -- so as a result that reference transcript ID might not appear in the output.

One could use gffcompare to map the output of StringTie (without -e) back to the reference annotation which would provide the details of the structural relationship between StringTie-assembled transfrags and the reference transcripts.

**Comment by mouyuemouri** [comment]
I ran into the same problem   in StringTie v2.1.1
