### ISSUE TITLE
With prefix "chr" and without prefix "chr" in the input bam files for assembly question

### ISSUE THREAD

**Issue by eudoraleer** [gpertea/stringtie#70]
Why would there be a difference in the output GTF file if I were to use GRCh38 to assemble bam files having "chr" as prefix for chromosome numbers vs to use GRCh38 to assemble bam files having no "chr" as prefix for chromosome numbers?

Thanks!

**Comment by gpertea** [comment]
Not sure I fully understand the question but it should be obvious that StringTie has to exactly match the chromosome names between read alignments (bam file) and the annotation -- we cannot just assume that "chr6" and "6" are always the same thing (e.g. in many unfinished genomes, "6" can be just the name of some contig or scaffold). While that might be true for human annotation, software like StringTie does not try to be "smart" that way, re-interpreting/correcting user input.. ("oh by 6 you meant chr6, right"?). 

Unless you meant there are structural differences in the assembled transfrags when both the BAM file and the annotation have the "chr" prefix versus both *lacking* that prefix -- in that case I would ask for an example because that would be a bug we should fix.
