### ISSUE TITLE
Stringtie --merge GFF Error: overlapping duplicate transcript feature

### ISSUE THREAD

**Issue by Kapeel** [gpertea/stringtie#71]
Hi, 

I am getting this error while try to merge the gtf files generated from stringtie. How do I resolve it.

`./stringtie-1.3.0.Linux_x86_64/stringtie --merge gtf.list -o test_merge`

GFF Error: overlapping duplicate transcript feature (ID=Sobic.002G119900.1.v2.1)

thanks

**Comment by Kapeel** [comment]
Thanks for the reply. I found more than 4 transcripts with duplicate ID's. I removed them from the sample gtf files . StringTie merge worked after removing them. I used STAR for alignment with reference annotation and then used stringtie with -G for annotation file. I will try again with a different dataset to see if the error occurs again.

**Comment by RestonV** [comment]
I am having a similar problem, but I am returning 0 or 1 from the input files and 0 for the reference file, is there any further troubleshooting you can provide?

**Comment by Kapeel** [comment]
I had a similar issue again with a different datasets. I ran stringtie with out the reference annotation file and then used the annotation file at the stringtie merge step.

**Comment by RestonV** [comment]
Just tried that with 3 different data sets, thanks for the help

**Comment by gpertea** [comment]
Version 1.3.1 which was just released should have fixed this, we hope -- it seems that in v1.3.0 there were situations where the -e option produced duplicate transcript IDs in the output.
So essentially this means re-running the -e step in the pipeline with the new version. Please report back if you still have these duplicate transcript issues with the new version.

**Comment by Michael-w-s** [comment]
I am having the same problem while running version 1.3.1b. When I looked there are duplicates being created by stringtie, what is the solution? Is there another update to prevent this?

**Comment by gpertea** [comment]
Sorry, forgot to mention this here too -- yes, please get 1.3.1c, should finally fix this issue.
Download it from: http://ccb.jhu.edu/software/stringtie/#install 
(or build from the master branch here)

**Comment by jenvik** [comment]
I'm still having the same issue when using stringtie-1.3.1c.Linux_x86_64 and the grep line mentioned as above doesn't return anything.  I will try only using the -G at the stringtie merge step and see if that helps.  Thank you!

**Comment by zhenyisong** [comment]
I have the same problem. When I used the shell script above to check if my specified  GTF file does have duplicate entry, the report returned 1. I also used most recent version of 1.31.1c.Linux64.

**Comment by gpertea** [comment]
I am trying to establish if this duplicate transcript issue happens the merge step or rather earlier in the pipeline (the files produced by `stringtie -e`, as it was shown to be the case before when we thought we fixed it). What is the transcript_id shown in the error message you get at the merge step? Does it look like it was a novel one produced by StringTie or it comes from the reference annotation?
In either case, could you check for that particular transcript_id in all the input files? (using fgrep as shown earlier). Since you mentioned it's not duplicated in the reference annotation file then it might be in one of the other input files produced by stringtie -e.  If that's the case, a fixed version of stringtie should be re-run for that sample.
     We are just testing v1.3.2 which has a few bug fixes and one of them might be related to printing duplicate transcripts in some situations -- you could download the pre-release version if you want to test it on a run which still had duplicates with v1.3.1c, we are grateful for your feedback. If you want to give this (not tested!) pre-release version a try, please download the source or the pre-built Linux binaries here:
 http://ccb.jhu.edu/software/stringtie/dl/stringtie-1.3.2-pre.tar.gz
 http://ccb.jhu.edu/software/stringtie/dl/stringtie-1.3.2-pre.Linux_x86_64.tar.gz

**Comment by zhenyisong** [comment]
The thrown-out error happened when I used '-G' option without '-e' because I want to pick out novel transcripts. The GTF annotation is from NONCODE database. The complained transcript_id i was from NONCODE database annotation.
I re-run my script without '-G' option, then everything was OK. BTW, Can the merge result have FPKM column? Again, thanks.

**Comment by zhenyisong** [comment]
The new version is OK.

**Comment by Mengist19** [comment]
Dear developer,
I have problem of GFF error  while I ran stringtie with merged.gtf (global.gtf). It is stringtie 1.3.3b 

GFF Error: overlapping duplicate transcript feature (ID=PGSC0003DMT400030180).

what can i do ? 
Thanks

**Comment by CarlosBarronG** [comment]
Kapeel how could you removed the duplicated transcripts from your file?

**Comment by Kapeel** [comment]
Since I had only 4 transcripts that had duplicate ID's. I removed them manually.

**Comment by CarlosBarronG** [comment]
Kappel, could you please tell me which command did you use to remove the duplicated ID´s? or step by step how could I remove them manually? 
Thanks for your comments I am having the same problems
