### ISSUE TITLE
Error with stringtie 1.3.1

### ISSUE THREAD

**Issue by JudithMarsman** [gpertea/stringtie#78]
I was using stringtie 1.3.0 which worked fine, but when I use the same codes for stringtie 1.3.1 I get an error. Stringtie 1.3.1 works fine following the tuxedo2 protocol up to the step where transcript abundances are estimated based on the merged transcript file, which is supposed to create table counts for use in Ballgown. This is the code I used:

stringtie -e -B -p8 -G merged.gtf -o output/sample1/sample1.gtf sample1.bam

Which gives me the following error:

Error at GBitVec: index 7 out of bounds (size 7)

Is there any solution for this?

**Comment by gpertea** [comment]
Ouch, this looks like a possible regression bug introduced with the latest changes. Annoying that we did not catch it in testing..
Ela spotted a piece of code where this could happen and submitted a fix, but we're not sure it's the one since we can't reproduce the error here on our test data sets -- but could you please please please try this quick-patched 1.3.1b version on your data above and let us know if it still errors like that:
http://ccb.jhu.edu/software/stringtie/dl/stringtie-1.3.1b.Linux_x86_64.tar.gz
(source: http://ccb.jhu.edu/software/stringtie/dl/stringtie-1.3.1b.tar.gz)
Many thanks!

**Comment by JudithMarsman** [comment]
Thanks for your help. I still get an error at the same step with 1.3.1b:

Error at GBitVec: index 11 out of bounds (size 11)

**Comment by gpertea** [comment]
Wow, wasn't this a bumpy release.. It looks like only now Ela found the actual cause of this bug in v1.3.1 so now the bug fix version v1.3.1c is out and ready for download at:
  http://ccb.jhu.edu/software/stringtie/#install
(direct link: http://ccb.jhu.edu/software/stringtie/dl/stringtie-1.3.1c.Linux_x86_64.tar.gz)

Thanks a lot for helping with this, the data set you sent was very useful.
Hopefully you can confirm this is now working without errors for you.

**Comment by JudithMarsman** [comment]
That works, thank you! The prepDE.py script also works on the output from Stringtie 1.3.1c. 
I do get different results (gene lists and counts) with versions 1.3.0 and 1.3.1c. Is the latter one supposed to be better?

**Comment by gpertea** [comment]
Yes it does, there were some adjustments to the estimation code that should account for the differences..

**Comment by DrChunLi** [comment]
Amazing efficiency. The 1.3.1c works great!

**Comment by AMMMachado** [comment]
Hi,
My mistake i open a new topic , but here its the correct place. I have the same kind of problem with Stringtie version 1.3.1.

Error at GBitVec: index 16 out of bounds (size 16)
Segmentation fault (core dumped)

The SAM file was generated with HISAT2 2.0.5 version with the --dta option and converted to BAM with samtools. We then run Stringtie (using 32 Gb of RAM) with the following command:

./stringtie -p 10 -G Mus_musculus.GRCm38.87.gtf -o SRR850587.gtf -l Mus_musculus SRR850587.bam

Cheers.
