### ISSUE TITLE
prepDE.py Attribute Error -- This time with Transcript_ID

### ISSUE THREAD

**Issue by jstrohm** [gpertea/stringtie#84]
Hello,

 I have 16 samples, and the script runs successfully for 8 of them, and fails with the following error for the other 8. They were processed with identical commands, and reference files for -G. I have attached the ballgown.gtf files for three samples that fail and three that run.  By chance the three that I selected to troubleshoot the previous gene_id error are ones that ran successfully with your recent update.

Traceback (most recent call last):
  File "./prepDE_update.py", line 85, in <module>
    t_id=RE_TRANSCRIPT_ID.search(v[len(v)-1]).group(1)
AttributeError: 'NoneType' object has no attribute 'group'

[success1.gtf.tar.gz](https://github.com/gpertea/stringtie/files/622751/success1.gtf.tar.gz)
[success2.gtf.tar.gz](https://github.com/gpertea/stringtie/files/622752/success2.gtf.tar.gz)
[success3.gtf.tar.gz](https://github.com/gpertea/stringtie/files/622755/success3.gtf.tar.gz)

[fail1.gtf.tar.gz](https://github.com/gpertea/stringtie/files/622758/fail1.gtf.tar.gz)
[fail2.gtf.tar.gz](https://github.com/gpertea/stringtie/files/622761/fail2.gtf.tar.gz)
[fail3.gtf.tar.gz](https://github.com/gpertea/stringtie/files/622762/fail3.gtf.tar.gz)

**Comment by jstrohm** [comment]
Additionally, for this file I get the following error:

Traceback (most recent call last):
  File "./prepDE_update.py", line 171, in <module>
    if v[2]=="transcript":
IndexError: list index out of range

[fail4_out_of_range.gtf.tar.gz](https://github.com/gpertea/stringtie/files/622792/fail4_out_of_range.gtf.tar.gz)

**Comment by gpertea** [comment]
What's your directory/file structure for the failed prepDE run(s) (and the prepDE command line) ? You mentioned 16 samples (or is it 8 at a time, under the same directory?) but if they are all under the the same directory, prepDE will stop at the first one which fails so I don't understand how you determined that it  works for _some_ samples but fails for specific _others_? .. Unless you keep moving  the sample directory that fails out of that base ballgown directory and then run prepDE again ?

I hope you realize that prepDE scans all the gtf files found 2 levels under the -i directory (.../ballgown_dir/sample_dir/*.gtf), and all these files must have been generated with the same merged.gtf file at the `stringtie -e` stage. If you mix and match multiple runs under the same directory you'll run into errors like you encountered above.

When I use the 7 samples that you just posted I don't get any errors, most likely because I don't run it the same way you did (on the same directory/files)..  With the files you provided, it works fine when I run it with this directory structure:
```
ballgown_test2
|-- 2-B5399_S1_mRNA_ART25_NGSLib2.BALLGOWN
|   `-- 2-B5399_S1_mRNA_ART25_NGSLib2.BALLGOWN.gtf
|-- 3-B5389_S1_1a_mRNA.BALLGOWN
|   `-- 3-B5389_S1_1a_mRNA.BALLGOWN.gtf
|-- 3-B5389_S1_AMY2P_NGSLib1d_mRNA.BALLGOWN
|   `-- 3-B5389_S1_AMY2P_NGSLib1d_mRNA.BALLGOWN.gtf
|-- 4-B7274_S2_AMY2P_NGSLib1d_mRNA-BALLGOWN
|   `-- 4-B7274_S2_AMY2P_NGSLib1d_mRNA-BALLGOWN.gtf
|-- 5-B7483_S2_mRNA_ART25_NGSLib2-BALLGOWN
|   `-- 5-B7483_S2_mRNA_ART25_NGSLib2-BALLGOWN.gtf
|-- 6-B7474_S3_1a_mRNA-BALLGOWN
|   `-- 6-B7474_S3_1a_mRNA-BALLGOWN.gtf
`-- 8-B7877_S4_1a_mRNA-BALLGOWN
    `-- 8-B7877_S4_1a_mRNA-BALLGOWN.gtf
```
So when I run `prepDE.py -i ballgown_test2` in the current directory (which parents ballgown_test2), it scans all these gtf files and finishes successfully.
  I hope you don't have other ballgown_dir/*/*.gtf files somewhere in that directory tree which might cause problems (the last IndexError message you showed me suggested that prepDE encountered a file which is not even properly tab delimited, as a GTF should be..)

If you cannot root out any such problems with your files or directory tree there, you should pack the whole directory tree with 8 (or fewer) samples which somehow cause prepDE to fail and send that whole archive to me, because the context is important here..

**Comment by jstrohm** [comment]
Yes after I noticed in the terminal printout that three samples ran successfully, and then it failed on the fourth, I was moving the sample directory that fails out of that base ballgown directory and then running prepDE again like you said for every sample. 

But the fact that you ran the command only with my gtf files, and commented that no other gtf files should be present, led me to figure out what I did wrong.

I misinterpreted the manual when it states that prepDE.py needs the ballgown files generated by -B. 

In each ballgown sample subdirectory, I was providing the other ballgown files such as: 

abund.tab
e2t.ctab
e_data.ctab
i2t.ctab
i_data.ctab
refs.gtf
t_data.ctab

I made a new directory tree that does not contain any of these files and the script ran successfully! Once again thanks for your rapid, detailed, and professional response!

**Comment by gpertea** [comment]
This seems to be an incorrect explanation of went wrong -- which is in fact blaming the -B option :) Those *.ctab files should be simply ignored by the prepDE script which only looks for *.gtf files in those directories.. Not sure what that "refs.gtf" file is in your listing but (certainly wasn't generated by stringtie, you probably copied it there yourself, right ?) but I'd rather suggest (and hope) that it was that (kind of) extraneous GTF file that caused the problems..

**Comment by jstrohm** [comment]
Weird... I never purposefully generated refs.gtf 

When you said that there shouldn't be any other gtf files, I indeed blamed them for causing the error. Sorry I didn't make that clear in my last post

I have no idea where they came from, but will make sure it doesn't interfere in the future.
