### ISSUE TITLE
prepDE.py --TPM vs cov

### ISSUE THREAD

**Issue by jstrohm** [gpertea/stringtie#85]
Hello,

Is it possible to have this script export the TPM values in the ballgown.gtf files instead of coverage?

**Comment by gpertea** [comment]
Sure it's possible.. But the purpose of prepDE was to write those tables with estimated *read counts* per transcript/gene and per sample, as required by other downstream DE analysis programs, not to copy attributes like coverage or TPM from the GTF file..
Indeed one could easily modify the script to just copy those TPM values instead of approximating the read counts from coverage.. Not a priority for us at this point though..
