### ISSUE TITLE
specify library type

### ISSUE THREAD

**Issue by shaomingfu** [gpertea/stringtie#86]
Hi,

As far as I understand, StringTie use the "XS" tag to predict the strandness of the transcripts. For strand-specific experiments, is it possible to manually specify the library type (i.e., ff-first, ff-second, fr-first, fr-second, or unstranded)? I could not find such parameter in the current version (v1.3.1c).

Thanks,
Mingfu

**Comment by gpertea** [comment]
No, there is no such option, I think I was kind of hoping the aligner would do this for us, but I agree that we should also support such an option, as it's not hard to make use of that info in StringTie when loading the alignments and we could assign the strand accordingly. We consider this as a useful feature to be implemented in a future release.

**Comment by shaomingfu** [comment]
Thanks for your reply!

As far as I know both TopHat and HISAT aligners support such library-type option, and these two aligners will thus give XS tag for every single line of the alignment when such information is given. Unfortunately, STAR does not do this. Suppose that I want to use both STAR and StringTie to assemble strand-specific RNA-seq dataset. Can I do it with the following procedure?

1, Use STAR to get the reads alignment (bam file).
2, Write a program to take the above bam file and strand-specific information (i.e., fr-first, fr-second, etc) as input, and add/replace a XS tag for every single line of the bam while keep all other stuff unchanged, and output a new bam file.
3, Run StringTie on this updated bam file.

Could you comment on this pipeline? Is it feasible?

Thanks!

**Comment by gpertea** [comment]
Definitely feasible, that's exactly what I would do if I were in your (unfortunate) situation of having to use STAR instead of HISAT2 with stranded libraries :-)
You could theoretically do all this on the fly -- i.e. without writing intermediate files, something like this:
```
samtools view -h star_alns.bam | addXS --fr-first | stringtie - ... (other stringtie options)
```
The basic idea is that stringtie will expect the (sorted!) alignments from _stdin_ (in SAM text format, header required) when the input file is given as '`-`' . Of course you have to write the _addXS_ script which would parse the SAM lines in order to inject the XS tag as needed before sending the lines to _stdout_.

**Comment by shaomingfu** [comment]
Got it! Thanks a lot!
