### ISSUE TITLE
Error at GBitVec: index 21 out of bounds (size 21)

### ISSUE THREAD

**Issue by preetin7** [gpertea/stringtie#90]
Hi,

I am using stringtie v1.3.2. I get this error only for a particular file. Please advise.

Thanks

**Comment by gpertea** [comment]
Could you please sharing that particular file and the StringTie command line which triggers this error?

**Comment by preetin7** [comment]
Here is the command I am using:
stringtie-1.3.2/stringtie -A S35.abundance -e -B -p 8 -G stringtie_merged.gtf -o ballgown/S35/S35.Pp3000_v3_gb.gtf 35.sorted.bam.bam -v. Should I attache 35.sorted.bam.bam file?

**Comment by gpertea** [comment]
I don't think large attachments work here.  Could you upload this (or the region of interest, see instructions below) to something like Dropbox, Google Drive or Box etc. If none of those are a good option for you, I can provide info about using ftp to upload to our server directly.
In order to limit the upload size (and not having to upload the whole .bam file), could you please extract just the region of the BAM which triggers the error? This can be determined by re-running StringTie with the same input files but with option `-v` and **without `-p 8`**; this should produce a log and the bundle region which triggers the error should be shown just before the error. Then you can extract a smaller BAM file with just the region of interest using a command like this:
 `samtools view -b 35.sorted.bam.bam chrN:XXXXX-YYYYY  > region.bam` 
(obviously replacing chrN:XXXXX-YYYYY with the actual bundle location).
Then upload the resulting `region.bam` file and the `stringtie_merged.gtf` file.
Thanks!

**Comment by preetin7** [comment]
Proceeded as advised and get the following error:

samtools view -b ../sortDIR/35.sorted.bam.bam LGTT01001370.1:2850-8573 > region.bam

[region.zip](https://github.com/gpertea/stringtie/files/722542/region.zip)
[bam_index_load] fail to load BAM index.
[main_samview] random alignment retrieval only works for indexed BAM files.
[stringtie_merged.zip](https://github.com/gpertea/stringtie/files/722544/stringtie_merged.zip)
Thanks 
T

**Comment by gpertea** [comment]
The .bam file has to be indexed before running that `samtools view` command:
 samtools index  ../sortDIR/35.sorted.bam.bam
After the index is created the region extraction command should work as expected.

(The region.bam file you gave me only has the SAM header, no alignments).

**Comment by preetin7** [comment]
[region.zip](https://github.com/gpertea/stringtie/files/722605/region.zip)
please find attached, thanks

**Comment by preetin7** [comment]
Hi, any updates please?

**Comment by gpertea** [comment]
Yes, I was about to write about this -- a fix was found and the fixed version (v1.3.2b) is available for download:
http://ccb.jhu.edu/software/stringtie/#install
(OSX binaries is coming in a few minutes).
Thanks for the example data, it was very useful for finding the bug.

**Comment by preetin7** [comment]
Thanks a lot :)
