### ISSUE TITLE
stringtie v1.3.2b takes ages to complete as comapred to v1.3.1c using the same file

### ISSUE THREAD

**Issue by bioinfo17** [gpertea/stringtie#92]
Hi,

Stringtie v1.3.2b seems to take ages to run and sometimes days. Using the same file, v1.3.1c finishes the job in couple of minutes. I would like to continue with v1.3.1c and if it crashes would switch to v1.3.2b. Will it affect my results using two different versions for certain files? Is it still ok to use v1.3.1c?

Thanks

**Comment by gpertea** [comment]
Wow, this is a new problem that I'd like to look at. Is it possible to share with us the data set which finishes in minutes on 1.3.1 but takes hours/days on v1.3.2b?

**Comment by preetin7** [comment]
Do you have an email address that I could send to?

**Comment by gpertea** [comment]
Yes, please use geo.pertea@gmail.com

**Comment by preetin7** [comment]
Files shared with you, I have a number of similar bam files, stringtie is running on this file since 9 hrs now. Please keep the gff file confidential, thanks :) Look forward to your reply.

**Comment by bioinfo17** [comment]
Any updates please?

**Comment by gpertea** [comment]
Ah, you are not checking your e-mail on your gmail account? I replied to that gmail account you used to share the Google Drive files, but since you did not apparently read that, here it is again:
What you shared with me was a large FASTQ file (17.fq) instead of the .BAM file you used. 
Please make sure you share the exact input files you used with StringTie and also the command line used to run StringTie on those files. Obviously 17.fq was NOT the input for StringTie -- it must have been a BAM file.

**Comment by bioinfo17** [comment]
Have emailed you :)

**Comment by gpertea** [comment]
OK what I see as a serious problem with your data (and your use of StringTie) is that what is supposed to be a "reference" annotation file (i.e. a curated set of trusted transcript structures that should *help* and indeed *guide* StringTie when assembling potentially messy read alignments) is instead a huge, eclectic combination of GFF records coming from multiple gene finders and aligners.:
```
  augustus_masked
  blastn
  blastx
  cdna2genome
  est2genome
  protein2genome
  repeatmasker
  snap_masked
  tblastx
```
Please don't use an unrefined collection of gene finders' output and protein/mRNA alignments as "reference annotation" for StringTie, this is actually the opposite of what "reference annotation" means. This does not "guide" the assembly of read alignments -- on the contrary, it's making things much worse!  It's like feeding another .BAM file as "reference annotation" and **expecting StringTie to untangle the reference annotation (!) too**, instead of helping with the untanglement of the RNA-Seq read alignments, which is the primary function of StringTie.  Please use a real gene combiner program to try to reduce and reconcile the entries in that GFF file into a refined and consistent set of gene/transcript models. If you do not have real reference annotation or at least a trusted and consistent gene combiner data set, **better not use any annotation at all (don't use the -G option)**, just let StringTie assemble the RNA-Seq read alignments and later use its assembled transfrags as input for a real gene combiner along with other sources of evidence that you have there -- if the goal is to build an annotation for a novel genome assembly, which is what your data seem to suggest here.

And indeed v1.3.1 was working with this messy "annotation" data because it was discarding most of those GFF objects.. Unfortunately v1.3.2b was made much more permissive in order to accept some otherwise unrecognized objects as "transcripts" due to some non-standard GFF objects from true reference annotation sources like NCBI's RefSeq (e.g. V_gene_segment and C_region features) which I wanted to preserve as "transcripts", in a structural sense.  But I did not expect that some users will "abuse" this new "openmindedness" of the GFF parser by feeding an unrefined bunch of alignments and gene finders' data into StringTie pretending to be "reference annotation"..

**Comment by gpertea** [comment]
It looks like using just "Ppluv-maker" track (and discarding everything else) might be the closest thing to a "reference annotation" in your example here. 
However it also looks like the GFF parser is now way too permissive, I guess it should've discarded all those "match_part" features and their parents (which is what v1.3.1 did). This is something I could fix and I guess I should..

**Comment by bioinfo17** [comment]
Thanks for the detailed explanation. And yes, I believe I should use only the "Ppluv-maker" tracks and disregard everything else and run stringtie again. Should I use v1.3.2b now or wait until you have fixed the "match_part" features issue which you did with v1.3.1?

Once again thanks for looking into my data and guiding me in the right direction 👍

**Comment by gpertea** [comment]
Just pushed out v1.3.2d which should take care of this issue, even if you use your original stuffy annotation file :).  
So please download and use this 1.3.2d version.  It still takes slightly longer than v1.3.1c to just parse the annotation file (few seconds more) as it tries to rescue any transcript-like features from that file (which 1.3.1c was not), but the actual number of "guides" eventually considered is now the same, and the actual read-alignment and transcript assembly time is the same as before (if not faster, for your small example data couldn't tell). 
So if you actually filter the annotation file in advance to only include the "Ppluv-maker" track you will actually save some time for each run as StringTie will load that smaller annotation much faster, obviously..

**Comment by bioinfo17** [comment]
Awesome!!!!!! will filter tracks as advised, thanks :)
