### ISSUE TITLE
Regarding MSTRG tag

### ISSUE THREAD

**Issue by eudoraleer** [gpertea/stringtie#98]
Hi Developer,

I saw that in some cases, the sam MSTRG tag is tagged onto two different gene names in the GTF output for merging the transcripts from all samples. Is that right? Also, how does prepDE.py calculate such that its final gene count and transcript count output files consider the mentioned case?

Thank you.

**Comment by gpertea** [comment]
This could happen in a couple of cases:
-  when a small gene is location-embedded within another gene (e.g. within an intron of another gene) and sometimes due to incomplete/partial splicing (or intron retention?) StringTie may assemble transcripts covering both the embedded gene and the exons of the encompassing gene
-  when one ore more assembled transcript is stretching across multiple adjacent loci; such a chimeric transcripts can be assembled by if, for example, there are read alignments that are [incorrectly] crossing the intergenic space between two genes which are close together on the genome

If could be useful to load the alignments (and/or the GTF) in a viewer to see for yourself which of the above are the case for your genes of interest.

And to your last question -- obviously the read counts for the genes and transcripts are going to be affected accordingly, prepDE doesn't care about gene names, it only sees the gene IDs and the transcripts with coordinates and coverages as given in the GTF.

**Comment by eudoraleer** [comment]
Thank you for your reply. In that case, does it also mean that I can consider them as noise in my data? I think without coordinates information, it will be a painful process to map the MSTRG IDs in the final gene count output to a reference GTF file.

**Comment by eudoraleer** [comment]
Just to show you an example:

![snip20170213_3](https://cloud.githubusercontent.com/assets/5945741/22878587/576a781c-f215-11e6-96c2-fb915a5c6f48.png)

**Comment by eudoraleer** [comment]
Hi developer, I guess prepDE will assign the same MSTRG tag for genes that falls within the same region / genes that falls in the same genomic location but one is on the plus strand and the other on the reverse strand.

**Comment by gpertea** [comment]
No, that should not happen - only exon overlaps on the *same strand* are considered when StringTie (and other programs like gffread etc.) groups transcripts under the same locus/gene.
As for the example you posted above, you should take a look at the transcripts assembled in that area for MSTRG.54661. The two genes there are on the same (forward) strand, and I am pretty sure that there are alignments/transfrags that overlaps both loci, that's why StringTie created a single large locus called MSTRG.54661 which encompassed both genes. 

> I think without coordinates information, it will be a painful process to map the MSTRG IDs in the final gene count output to a reference GTF file.

Yes, most of the time data are noisy, and if the experiments were not planned properly it might get "painful", for example, to remap IDs between separate analyses which should've been done together in the first place etc.

**Comment by eudoraleer** [comment]
How do you deal with cases like this? If I found a set of genes tagged with MSTRG tags only, and some of them have difficulties assigning gene names, say, MSTRG.54661 tag that encompassed both genes, how would we like know which is the gene that which is expressing high, gene 1 or gene 2? Coordinate information are already lost, either in ballgown output or prepDE output (samples ran in the same analysis).
