### ISSUE TITLE
Gene count output from prepDE.py

### ISSUE THREAD

**Issue by eudoraleer** [gpertea/stringtie#99]
Hi Developer,

I was wondering, normally gene count output will consist of the counts for isoforms of genes, I assumed that it is the same for prepDe.py. I looked through the gene count output and saw that many of the entries are labeled with ENSG tags instead of ENST tags. Does it mean that counts for all isoforms of a particular gene will be summed up and show under its ENSG tag entry for each sample?

Also, some entries in the gene count output does not occur to be like that, for the same gene with different MSTRG tags (but not tagged with ENST or ENSG tags) (isoforms) are not combined.

Thanks.

**Comment by gpertea** [comment]
- I don't get what you mean, ENSG prefix is typical for Ensembl gene IDs, so it should be expected in the gene count table, which shows counts by _gene ID_.
- so yes, summing up the counts for all transcripts in a gene should give the read count (estimates) for the gene

> some entries in the gene count output does not occur to be like that, for the same gene with different MSTRG tags (but not tagged with ENST or ENSG tags) (isoforms) are not combined

Perhaps it would help to provide a brief example. You mean "same gene *name*" but different MSTRG._gene#_ gene IDs ? It is possible to have an opposite situation to the 'two gene names with the same MSTRG gene ID' that you asked about in issue #98: a single, long gene region where StringTie found two isolated bundles of read alignments (maybe due to a region of low coverage, or problematic alignments?) so it could "split" it into two distinct loci (hence two gene IDs were assigned, even though they might both overlap some reference gene). 

StringTie looks at the "evidence" for each locus (read alignments, or transcripts in the case of `--merge`) and only groups the resulting transcript assemblies under the same MSTRG._gene#_ **if** there is any **exon overlap** between these resulting transfrags. As I mentioned earlier, StringTie and prepDE do not care about gene names as those cannot be relied upon for providing locus information (you can have the same gene name in different locations of the genome).

**Comment by eudoraleer** [comment]
Thank you for your reply. Yes I meant the same gene name with different MSTRG tags. If so, since the gene count output from prepDE.py consists of counts labeled with MSTRG IDs (except for those labeled with ENSG IDs), how do we know if those MSTRG IDs refer to the same gene if sometimes the same gene name can be reference with different MSTRG tags? Or the case in which the same MSTRG ID may refer to a different gene [Issue 98](https://github.com/gpertea/stringtie/issues/98) ? Because eventually I have to map the entries labeled with MSTRG IDs to match their gene names (coordinate information is lost in the gene count output of prepDE.py).

**Comment by gpertea** [comment]
Coordinate information is not lost, unless you lost the GTF you used as input :).  So the coordinates for each transcript for each gene_id you see in the gene count output can be retrieved, if needed. Yes, you might have to write a script to do this mapping from gene_id to coordinates, or "gene_name" attributes or whatever other information you might need to retrieve from that GTF. 

`gffread` might actually help a bit with that, if you use the `-M` or `--cluster-only` option with that GTF (remember `-o`, otherwise you won't get any output), you'll get new `"locus"` features created for any overlapping transcripts, and its coordinates will reflect the actual genomic span of each such cluster (locus), and all transcript_ids and gene_ids found to belong to that locus will also be listed as comma delimited lists for the `"transcripts"` and `"geneIDs"` attributes, respectively. All the gene names found for each locus will also be listed in the `"genes"` attribute.
